### ISSUE TITLE
Does this support react-native?

### ISSUE THREAD

**Issue by soliury** [reduxjs/redux-devtools#10]

**Comment by hzoo** [comment]
Not yet? https://github.com/gaearon/redux-devtools/blob/a30043f54ef0d434174d80e36c963d80ce7d1b3d/src/react/native/index.js

**Comment by soliury** [comment]
Ok, I see.

**Comment by gaearon** [comment]
@jlumpe Any chance I could get you to port the internal prototype you did to this stable code version? Shouldn't require many changes I think..

**Comment by johanneslumpe** [comment]
Yeah I'll try and take a look asap :)

**Comment by soliury** [comment]
@gaearon I have used the redux in a react-native app---[noder](https://github.com/soliury/noder-react-native), But I have some problems:

* Is there can be two connectors in a redux app?

* I put the Navigator in the connector, is this a  good way?

* Is there any react-native Example code for use redux, I mean I know how to use, but I don't know this is the best way.

* Look into my [noder](https://github.com/soliury/noder-react-native) , component nest component, and the state is passed through many component, I think this will result in some Performance issues especially in react-native. Can you give me  some advice?

**Comment by gaearon** [comment]
@soliury

This is a repository for Redux DevTools, not for Redux. Can you please ask these questions in the main Redux repo?

https://github.com/gaearon/redux

**Comment by soliury** [comment]
ok, I see.

**Comment by leoasis** [comment]
Any updates on this one? @johanneslumpe anything you're stuck with that may need help?

**Comment by timdoes** [comment]
Yes, this would help out tremendously!

:+1:

**Comment by grabbou** [comment]
Anybody working on this? If not, we might take a look into it as we are going to release new este/native with Redux, cc: @steida

**Comment by gaearon** [comment]
If you need any help let me know!

**Comment by grabbou** [comment]
Good, we kinda need it for WebExpo conference this weekend, so will keep you updated :)

**Comment by steida** [comment]
Yeah, we should help.

**Comment by gaearon** [comment]
Note: changes in #132 will make it harder to make an RN version until React 0.14 comes out and React Native releases a compatible update. 0.14 is coming soon, so I'd expect #132 to land about the same time it's ready. In the meantime feel free to experiment with the current (`2.x`) version which should be easier to get running with RN.

**Comment by GantMan** [comment]
Learning RN and Redux looks amazing.  I'm eager to test this!

**Comment by ms88privat** [comment]
any news on this?

**Comment by gaearon** [comment]
No news but feel free to work on this.
I personally don't have the time right now.

**Comment by GantMan** [comment]
As a heads up to all on this thread.  I'm a long time dev, but new to React.  If someone thinks they can get me pointed in the right direction with minimum screenshare training, I'll put the time in to try to get this going.  :beers:

**Comment by gaearon** [comment]
I think the most promising way to support this would be to try to make the [Redux DevTools Chrome extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) to play with React Native. 

Unfortunately DevTools currently uses React Redux 4.x which is incompatible with React Native as it still has its own fork of React. I can't give much more advice than that. I'm sure you'll figure something out if you give it some time :-)

**Comment by morenoh149** [comment]
so we should accelerate react native's transition to using the regular react package instead of a fork? that's what's blocking this?

**Comment by grabbou** [comment]
There's actually nothing to accelerate since that's ongoing issue and it's going to land super soon. (Afaik)

**Comment by zalmoxisus** [comment]
Implemented in [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools).

**Comment by corbt** [comment]
@zalmoxisus's solution works great. It would be ideal to merge his changes into the base redux-devtools though.

**Comment by zalmoxisus** [comment]
@corbt, actually I didn't make any changes in `redux-devtools`, I use the original [`redux-devtools/lib/instrument`](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/configureStore.js#L2) there.

The remote monitoring is meant to be used for React Native, hybrid, desktop and server side apps. For web apps it's easier and way faster to use the classic solution or Chrome extension (in `v1.0` we'll have there remote monitoring, but as an option).

**Comment by corbt** [comment]
@zalmoxisus ok, I guess as long as any changes/enhancements to the instrumentation are available to the `redux-remote-devtools` as well it isn't a big deal if we have to use a separate package in RN vs webapps.

**Comment by scarlac** [comment]
A quick update for those wondering/got here by Google:
The [Chrome extension](https://github.com/zalmoxisus/redux-devtools-extension) seems to be working with React Native now. Requires `npm install --save-dev remote-redux-devtools` and pressing the toolbar button and using "Open Remote DevTools".

It's not bug-free (it looses the connection when the app is reloaded) but it works for now. One annoying issue is that you need to reload the DevTools when the app reloads (it loses connection).

**Comment by zalmoxisus** [comment]
@scarlac, that issue should be fixed. Thanks for the report.

BTW, apart from the extension there's a [great ecosystem](https://github.com/zalmoxisus/remote-redux-devtools#monitoring) around this. You can [have Redux DevTools right on React Native Debugger](https://github.com/jhen0409/remote-redux-devtools-on-debugger). Or there's a [`React Native Debugger`](https://github.com/jhen0409/react-native-debugger), which includes both Redux DevTools and React DevTools.

**Comment by BerndWessels** [comment]
I use [React Native Debugger](https://github.com/jhen0409/react-native-debugger) with the following code and it works perfectly with `react-native 0.40.0` (even on Windows), no need to install anything else:

```js
    if (__DEV__) {
        // Development mode with Redux DevTools support enabled.
        const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
                // Prevents Redux DevTools from re-dispatching all previous actions.
                shouldHotReload: false
            }) : compose;
        // Create the redux store.
        store = createStore(rootReducer, composeEnhancers(...enhancers));
    } else {
        // Production mode.
        store = createStore(rootReducer, compose(...enhancers));
    }
```

**Comment by GantMan** [comment]
just a heads up, we've been using this forever in React Native.  If you're a fan of dev tools for redux, this is my fav.

https://github.com/infinitered/reactotron

**Comment by morenoh149** [comment]
ok great sounds like we can use redux-devtools with RN, this issue can be closed
