### ISSUE TITLE
Make state tree alphabetically sortable

### ISSUE THREAD

**Issue by pavelvrublevskij** [reduxjs/redux-devtools#1001]
This is proposition to have state tree sortable. Could be activated by some option.

Current state:
![image](https://user-images.githubusercontent.com/49069243/148765647-0deeddf6-71a8-4859-8b0e-08736d4ffaf8.png)

Expected:
alphabetically sortable state slices

**Comment by Methuselah96** [comment]
Thanks for the suggestion. This has already been suggested in https://github.com/reduxjs/redux-devtools/issues/433 so I'm going to close this for now just to keep the conversation centralized in that other issue.
