### ISSUE TITLE
Immutable object not parsed in v3

### ISSUE THREAD

**Issue by droid001** [reduxjs/redux-devtools#1006]
With the new version I cannot see the immutable data which is in the store. Instead the data looks like `$jsan(pin): "$[0][1]"`.

v.3:
![Screenshot 2022-01-12 at 10 27 55](https://user-images.githubusercontent.com/7068571/149107641-88df870a-35f2-4c06-a2b2-39f4235b0dbb.png)
v.2.17.2
![Screenshot 2022-01-12 at 10 27 24](https://user-images.githubusercontent.com/7068571/149107922-89c64e68-8fd9-41f7-a30c-5136b1c1f6c1.png)

On FF 96.0b10, MacOS 12.0.1

**Comment by Methuselah96** [comment]
@droid001 Any updates on whether the demo site works for you?

**Comment by droid001** [comment]
@Methuselah96 I see all the immutable values in the demo. And sorry for the late reply.
I'll have a closer look at how the object is populated. Just to mention I had the same experience with Opera 83.0.4254.19

**Comment by droid001** [comment]
I can now report that this is an occasional occurrence as the immutable object is shown correctly. Can this be a memory optimisation on part of the dev tools to not always show a whole immutable object?

**Comment by Methuselah96** [comment]
Not that I'm aware of. Is there a particular case that you can reproduce consistently? It'd be great to get to the bottom of this.

**Comment by Methuselah96** [comment]
@droid001 Anything else I can do regarding this issue?

**Comment by Methuselah96** [comment]
I'm going to go ahead and close this, but feel free to reply if you have any new information to help reproduce this issue and I can reopen it.
