### ISSUE TITLE
React DevTool doesnt connect to store

### ISSUE THREAD

**Issue by noypitt** [reduxjs/redux-devtools#1009]
We are using the following package(import { NgReduxModule, NgRedux, DevToolsExtension } from '@angular-redux/store';
 ) in order connect to redux devtool, starting a few days ago we are not able to connect to store:

 ```
constructor(
    private ngRedux: NgRedux<SplashState>,
    private devTools: DevToolsExtension,
  ) {
    ngRedux.configureStore(
      rootReducer,
      INITIAL_STATE,
      [],
      isDevMode() && devTools.isEnabled() ? [devTools.enhancer()] : []);

    // Enable syncing of Angular form state with our Redux store.
    provideReduxForms(ngRedux);
  }
}
```
I am not able to connect to store anymore.
![image](https://user-images.githubusercontent.com/69755366/149206999-3f5873b6-4f61-4fe4-8820-8d10425499f9.png)
What changed?

**Comment by Methuselah96** [comment]
What version of `@angular-redux/store` are you using? I believe you have to be on 10.0.0 in order for the latest Redux Devtools to work since earlier versions rely on the deprecated `window.devToolsExtension`.

**Comment by noypitt** [comment]
Thanks, we are in 9.0.0 tried to upgrade and gets a lot of errors.
Everything works till last few days. Any chance to make it work ?

**Comment by Methuselah96** [comment]
Sorry, we can't keep maintaining deprecated features forever and unfortunately there's no way to downgrade a Chrome Extension. I would highly suggest you upgrade to `10.0.0`. The only other workaround is to download the `extension.zip` artifact from [the most recent release](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/2.17.0) and [load it unpacked](https://stackoverflow.com/a/24577660/5327429). Sorry for the inconvenience.

**Comment by mavrikio** [comment]
https://reactnative.dev/docs/next/other-debugging-methods

Remote debugging must be enabled to connect with react native debugger.

To do this, you need to import...

import NativeDevSettings from 'react-native/Libraries/NativeModules/specs/NativeDevSettings';

And add the following code to your main component:

const connectToRemoteDebugger = () => {
        NativeDevSettings.setIsDebuggingRemotely(true);
};
