### ISSUE TITLE
[bug] in a old product redux view is empty when devtools 3.0.3 updated

### ISSUE THREAD

**Issue by hazeFlame** [reduxjs/redux-devtools#1014]

**Comment by Methuselah96** [comment]
Is it possible that you're using the deprecated `window.devToolsExtension`? `window.devToolsExtension` was [renamed](https://github.com/reduxjs/redux-devtools/tree/main/extension#usage) to `window.__REDUX_DEVTOOLS_EXTENSION__` / `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.

**Comment by Methuselah96** [comment]
@hazeFlame Did that fix your problem?

**Comment by hazeFlame** [comment]
@Methuselah96 yeah thanks，displayed a few days ago
