### ISSUE TITLE
On narrow view ports, unable to scroll to the right to select "RTK query" tab

### ISSUE THREAD

**Issue by sshquack** [reduxjs/redux-devtools#1018]
### Versions

- Firefox 96.0 / Chrome 97.0
- redux-devtools 3.0.3
- macOS 12
- Apple M1 chip

### Problem
I typically have redux-devtools running in a narrow viewport on the right handside of the app (as shown in the video). Once in the narrow viewport, I'm unable to either scroll or "view more" without resizing the redux-devtools window. Here is a demo of the problem:

https://user-images.githubusercontent.com/5678459/149644098-92e7768a-bc0c-4284-92fd-6a90b16e6856.mp4

### Potential solution
Currently both Firefox and Chrome show a nice ">>" button that shows the overflow tabs. Perhaps redux-devtools could use a similar strategy to make the experience consistent with the browsers.
<img width="1168" alt="Screenshot 000044@2x" src="https://user-images.githubusercontent.com/5678459/149644114-ad997e87-898a-40b8-a9ee-0082c27f8005.png">

**Comment by Methuselah96** [comment]
Thanks for the issue! This has already been reported/requested in https://github.com/reduxjs/redux-devtools/issues/919 so I'm going to close this just to close just to keep the conversation centralized.
