### ISSUE TITLE
Chart is not visible, because window is too small and not resizable

### ISSUE THREAD

**Issue by oveits** [reduxjs/redux-devtools#1029]
The chart is not visible, since the tool window is way too small:
![image](https://user-images.githubusercontent.com/8299115/149816474-933556c3-6445-478d-9aef-f6d403de9f9c.png)

On the lower right, there are some lines that show that the chart is there, but it is not displayed correctly.

Can we resize the window? I just do not know, how. The mouse pointer does not show any effect, when I hover over a corner of the tool window.

**Comment by oveits** [comment]
Okay, I have found out that the chart size can be changed:
![image](https://user-images.githubusercontent.com/8299115/149817270-8326d3dc-9c04-4074-99c5-60df4a70b699.png)

A resizable window would be much better, though, since the chart data is not readable this way. The only way to work with it is to move the chart by dragging it and to resize the chart locally with the mouse wheel. However, you only get a very small part of the overall chart.

I guess, with the chart resize feature, this bug is no bug, but I should open a feature request for adding the possibility to resize the tool window? When using a 4k screen, the tool window really looks tiny.

**Comment by Methuselah96** [comment]
You can open the Redux DevTools in a new window using one of the three "border" buttons in the bottom-right. You can also view the Redux DevTools as a tab in the Chrome DevTools (which you can undock as a separate window). Both of those options are resizable. Does that help?

**Comment by oveits** [comment]
I now have found how to open the tool in a resizable window:
Extensions Icon --> click the three vertial dots on the right of Redux DevTools --> choose "To left", "To right", "To bottom" or "Open in a panel"
With all four options, Reux DevTools opens in a resizable way.

**Comment by oveits** [comment]
@Methuselah96 : yes, that works as well. Thanks a lot for the quick response.
