### ISSUE TITLE
ReduxDev tools shows error on Jira

### ISSUE THREAD

**Issue by Tomsprakse** [reduxjs/redux-devtools#1033]
Hello,

Trying to open Jira on chrome with ReduxDev tools i get error message, "failed to initialize package jsutil TypeError: g.object is not a function"
when i turn off extension the problem disappears. 
On other browsers there is no issue. Maybe the issue is known and have some possible fix for this.

Thank you in advance.

**Comment by Methuselah96** [comment]
Thanks for the issue, let's keep this centralized in https://github.com/reduxjs/redux-devtools/issues/1032.
