### ISSUE TITLE
Map object is not supported in redux devtools #3293

### ISSUE THREAD

**Issue by mejakm** [reduxjs/redux-devtools#1034]
## Minimal reproduction of the bug/regression with instructions:

My state with a Map inside:

![image](https://user-images.githubusercontent.com/14975302/149959152-388d454f-27c5-4f7f-bbee-909815fae78b.png)

After dispatching the action and getting the response in my devtools it shows that my state is empty while in fact it's not.

![image](https://user-images.githubusercontent.com/14975302/149959375-1d36101a-1c57-4020-a77d-b3b1094ae840.png)

This is the console log after subscribing to my state slice:

![image](https://user-images.githubusercontent.com/14975302/149959503-51b31b3f-1d11-46e8-be11-d2060c7edfcf.png)

## Expected behavior:

It should show the real state 

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 13.0.1
Angular: 13.1.1
Browser: Chrome
OS: Windows

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by markerikson** [comment]
FWIW we have _always_ recommend _against_ putting non-serializable values like `Map` and `Set` into your Redux state, and this is specifically one of the reasons why.  Not sure if the NgRx docs list a similar restriction, but here's what we say on the Redux side:

https://redux.js.org/style-guide/style-guide#do-not-put-non-serializable-values-in-state-or-actions

**Comment by mejakm** [comment]
> 

I know it's recommended using only serializable objects but unfortunately most of our projects due to their complexity using `Map`and `Set`is a much better idea and it would be great if Redux Devtools would support them for easier debugging

**Comment by Methuselah96** [comment]
There is an option to enable serializing non-JSON objects (serializing `Map`s is not enabled by default). See the [`serialize` option](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md#serialize) (set `options` to `true`) in order to enable serializing `Map`s for the Redux DevTools extension.

Let me know if that works for you. Closing for now as I believe this is resolved.

**Comment by mejakm** [comment]
> There is an option to enable serializing non-JSON objects (serializing `Map`s is not enabled by default). See the [`serialize` option](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md#serialize) (set `options` to `true`) in order to enable serializing `Map`s for the Redux DevTools extension.
> 
> Let me know if that works for you. Closing for now as I believe this is just a matter of enabling that option.

Thanks, it works.

I added this line: `serialize: { options: { map: true } }` to the `StoreDevtoolsModule` options in `app.module.ts`
