### ISSUE TITLE
Upgrade to Manifest V3

### ISSUE THREAD

**Issue by timdorr** [reduxjs/redux-devtools#1037]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

While there are a lot of controversies around the new manifest format, I don't believe most affect us. The advantages are getting ahead of enforcement later (we've got a year until V2 extensions stop working) and getting into a faster approval workflow for updates on the Web Store.

Probably the most consequential is the move from background pages to service workers. Since we maintain a store on the background page, that logic will need to be persisted. We can probably get fancy and wrap some of the ways we access that store to lazy load it from storage (`window.store -> getStore()`). Here are the docs on migrating to SWs: https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

I don't think there's much else that affects us. Some minor things around `actions` changes, but that's mostly just moving stuff around in the `manifest.json`.

Edit: Pinning this since it's got a deadline associated with it. We'll have to take this seriously.

**Comment by respectYourNeighbour** [comment]
I also get some warning regarding this:
- Permission 'notifications' is unknown or URL pattern is malformed.
- Permission 'contextMenus' is unknown or URL pattern is malformed.

**Comment by dzienisz** [comment]
https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd I got info today that this extension will be removed soon.

**Comment by Methuselah96** [comment]
What info and how soon? I am actively working on this in my free time, but it's not a trivial upgrade.

**Comment by Jamescan** [comment]
This is what appears for me in `chrome://extensions`

![Screenshot 2024-07-30 at 12 53 34 PM](https://github.com/user-attachments/assets/97516558-72a7-4da9-8710-037640244683)

**Comment by Methuselah96** [comment]
Tracking progress in https://github.com/reduxjs/redux-devtools/issues/1705.
