### ISSUE TITLE
Unable to save 'Site access' setting in Google Chrome extension

### ISSUE THREAD

**Issue by motionltd** [reduxjs/redux-devtools#1039]
The setting is permanently set to 'On click', I did have it set to 'On all sites' by default, but changed it to 'On click' yesterday to get Jira Cloud to work while you were dealing with that lodash issue. Now with version 3.0.5 it's permanently set to 'On click', if I change it, it doesn't save the change.

I have tried uninstalling and reinstalling the extension, I have also tried updating other extensions to see if it was maybe a Chrome issue I was having.

https://www.loom.com/share/086c574bfc974cd1ae7bf1bc233ba2d5

**Comment by Methuselah96** [comment]
This isn't a setting that the Redux DevTools controls, so I believe this is actually a Chrome bug. I noticed [a Reddit post](https://www.reddit.com/r/chrome/comments/s67ajq/chrome_extension_site_access_settings_stuck_on_on/) where someone has a similar problem.

Let me know if there's anything else I can do to help.
