### ISSUE TITLE
False positive react site when redux-devtools is enabled

### ISSUE THREAD

**Issue by dhavall08** [reduxjs/redux-devtools#1042]
When this **redux devtools** is enabled, in most of the sites, the **react dev tools** indicates that the site uses React even though the site doesn't have React. Disabling this extension shows the correct status in **react dev tools**. 
However, it functions correctly in Firefox but not in Chrome. (I tried keeping only these two extensions in incognito). 
Example sites to look: https://angular.io/, https://meet.google.com/, ...

**Comment by Methuselah96** [comment]
This is fixed in [3.0.6](https://github.com/reduxjs/redux-devtools/releases/tag/remotedev-redux-devtools-extension%403.0.4) which is being rolled out throughout the day today.
