### ISSUE TITLE
Filter query saved, but not displayed in input on reload

### ISSUE THREAD

**Issue by taeram** [reduxjs/redux-devtools#1059]
Expected Behaviour:
1. Open up the Chrome Developer Tools 
1. Click the Redux tab
1. See that the "filter..." input is empty, and all actions are displayed
1. In the "filter..." input, type: Fetch
1. See that the results are filtered correctly
1. Reload the page
1. Open up the Chrome Developer Tools 
1. Click the Redux tab
1. See that the "filter..." input is empty, and all actions are displayed

Actual Behaviour:
1. Open up the Chrome Developer Tools 
1. Click the Redux tab
1. See that the "filter..." input is empty, and all actions are displayed
1. In the "filter..." input, type: Fetch
1. See that the results are filtered correctly
1. Reload the page
1. Open up the Chrome Developer Tools 
1. Click the Redux tab
1. See that the "filter..." input is empty, **but actions are still filtered by "Fetch"**
1. Type "asdf" into the "filter..." input
1. Clear the "filter..." input
1. See that all actions are displayed

**Comment by moniuch** [comment]
This has been closed, yet it doesn't appear solved.

![v3 0 9](https://user-images.githubusercontent.com/681956/152126278-6231349c-ebdc-4971-b29b-ca42b2eed23e.png)

Filter `load` that had been applied back in 3.0.5 is still applied after many page reloads.

Fresh update, to 3.0.9, new window, (new font :( )

**Comment by Methuselah96** [comment]
This has not been closed since it's still unsolved.

**Comment by moniuch** [comment]
@Methuselah96 You're right, my eye got tricked by the related issue status label :)

**Comment by wilfredmifsud** [comment]
Still happening
