### ISSUE TITLE
react-json-tree - Broken import statement in d.ts

### ISSUE THREAD

**Issue by edzis** [reduxjs/redux-devtools#1087]
When I use react-json-tree in a project with TypeScript 4.4 I get the following error:
```
ERROR in node_modules/react-json-tree/lib/types/index.d.ts:3:15
TS1005: ',' expected.
    1 | import React from 'react';
    2 | import PropTypes from 'prop-types';
  > 3 | import { type StylingFunction, type StylingValue, type Theme } from 'react-base16-styling';
      |               ^^^^^^^^^^^^^^^
    4 | import { CircularPropsPassedThroughJSONTree } from './types';
    5 | interface Props extends CircularPropsPassedThroughJSONTree {
    6 |     data: any;
...
```

<img width="744" alt="Screen Shot 2022-02-16 at 09 25 43" src="https://user-images.githubusercontent.com/163636/154216613-736df906-02e6-4350-9c08-84013357e97f.png">

---

If I convert that line to `import type { StylingFunction, StylingValue, Theme } from 'react-base16-styling';` it works without errors. That is the syntax defined in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by Methuselah96** [comment]
Yup, fair enough, this way of defining imports wasn't added until [TypeScript 4.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names).
