### ISSUE TITLE
Out of Memory randomly on pages

### ISSUE THREAD

**Issue by JaapioNL** [reduxjs/redux-devtools#1107]
After installing this plugin pages I noticed that chrome started giving "Out of Memory" error pages while visiting pages with react. Not all of the times but some times. After uninstalling the plugin the error message didn't show up anymore. Am I the first to experience this?

Is there anything I can supply to help figure out what is going wrong?

**Comment by Methuselah96** [comment]
Is your state large? Take a look at [this FAQ](https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/Troubleshooting.md#excessive-use-of-memory-and-cpu). Does that answer your question?

**Comment by JaapioNL** [comment]
Oops, looks like I posted in the wrong tab. @Methuselah96 thanks anyway :-)
