### ISSUE TITLE
Improve RTK Query monitor to focus more on data

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-devtools#1126]
Quoting user feedback in https://github.com/reduxjs/redux-toolkit/discussions/2206 :

> I've gotten used to using the "state" tab in the redux dev tools, where I can see the current state at a glance. However, with the rtk query dev tools, I need to click through multiple nested objects in order to get to the data field for a query, meaning that I often resort to console.logging the data rather than using the dev tools. I realize that technically rtk query saves lots of other types of state, but most of the time, I'm only interested in the `data` that is actually being used in my app.

Here's the current UI:

![image](https://user-images.githubusercontent.com/1128784/161867771-8a25152a-0fa3-49ab-829e-a4027fb602e8.png)

I think it might be worth having, say, "Data" and "Cache Entry" (TBD?) tabs.  One way or another, the actual data _should_ be immediately visible as soon as you click on the request entry in the list.

Tagging @FaberVitale for further thoughts.

**Comment by Bezmehrabi** [comment]
Hi! Can I give it a try?

**Comment by markerikson** [comment]
@Bezmehrabi Sure, please do!

My initial thought here (and @Methuselah96 or @FaberVitale please correct me if you have better ideas) would be that we add a new "Data" tab that shows _just_ the result data (and _maybe_ the "status" field too?), then make that "Data" tab the default.  We can leave the existing "Query" tab as-is, but users would have to click to it specifically to see the other details.

**Comment by Bezmehrabi** [comment]
what do you think about showing the "status" and either "data" or "error" (depending on whether request succeeded or not)?

**Comment by markerikson** [comment]
That seems good to me, yeah. In other words, let's focus on those. the two most critical pieces of info we care about with the request: status and contents.

**Comment by Bezmehrabi** [comment]
Hi, I did it and here's the UI:

![rtk-data](https://user-images.githubusercontent.com/46019949/162269059-d3b74eae-03b5-402e-a17d-acfd286499b9.png)
![rtk-data-full](https://user-images.githubusercontent.com/46019949/162269064-4848b7ed-b20b-4591-8bc5-0263a263bbef.png)


couple of questions:

1. right now the logic is:  if `status` is `fulfilled` show `data`, if it's `rejected` show `error`, otherwise only the `status` will be shown. is that good? or we wanna just show all these three properties no matter what?
2. I wrote the `QueryPreviewData` component in the functional way but other components are in written in good old class fashion, should I write this one with classes too or It's ok to be functional :))?

**Comment by markerikson** [comment]
This seems pretty reasonable to me!  This may be what you're doing already - I'd suggest ensuring that _if_ there's a `data` or `error` field, that it starts expanded by default if it's an object or an array.  Might as well save users that first click :)

And yeah, function components are good here.

**Comment by Bezmehrabi** [comment]
Yeah it's happening already :)

Alright then! Will add a couple of test for it and make the PR.

Thanks.

**Comment by Bezmehrabi** [comment]
Ok, I wanted to start writing tests for it but I noticed that `redux-devtools-rtk-query-monitor` has no test.
is it something intended??
If not so, I will add test configs and stuff.

**Comment by markerikson** [comment]
I'm not familiar with the code in this repo, so I don't know what the test setup is like atm. Adding tests does seem reasonable.

**Comment by FaberVitale** [comment]
There's not currently enough horizontal space for a "data" tab.

<img width="710" alt="Screenshot 2022-04-08 at 19 12 07" src="https://user-images.githubusercontent.com/16583125/162489895-cc2cd664-d76f-4042-8966-6f6df8a486b8.png">

**Comment by markerikson** [comment]
Hmm. tbh I've _never_ used the DevTools from that button :)  I always keep the entire browser devtools popped out as a separate top-level window.

Honestly, I see "view data" as _far_ more important than "tags" or "actions"  That should be the highest priority thing.

If anything, the DevTools UI should be made more responsive so that if there isn't enough room, it moves the rest of the tabs into an overflow area.

**Comment by markerikson** [comment]
Personally, I'd say ship the update basically as-is for now, and handle the tabs responsiveness in a follow-up issue.

**Comment by Bezmehrabi** [comment]
I made the PR :))).

**Comment by Bezmehrabi** [comment]
I also faced the `framer-motion` problem of demo.
It's a temporary issue because of webpack version 5.71 (It's works fine with 5.70).
so I don't think downgrading the `framer-motion` is necessary.

**Comment by Methuselah96** [comment]
@FaberVitale Since @Bezmehrabi expressed his intent to work on this task first, can you help review their PR and then you can make any changes you would like in a follow-up PR?

**Comment by Bezmehrabi** [comment]
any updates on this?
