### ISSUE TITLE
PROBLEM with configureStore

### ISSUE THREAD

**Issue by Dhruv-praju** [reduxjs/redux-devtools#1156]
Devtool is not working with **configureStore** .
`
import { configureStore } from '@reduxjs/toolkit'
const store = configureStore(rootReducer,  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__())
`

**Comment by losh11** [comment]
hey @markerikson I'm in the middle of migrating to a newer version of redux, with createStore being removed instead for `configureStore({reducer: persistedReducer})`. will this change also mean DevTools-extension is ready to use?

https://redux.js.org/usage/configuring-your-store#integrating-the-devtools-extension If so the redux documentation is really confusing? I believe this is trying to explain how configureStore works, and not how the user should implement devtools-extension?

**Comment by markerikson** [comment]
@losh11 Yeah, we ought to update that docs page some.

Short version is, `configureStore` automatically sets up the Redux DevTools integration, no further effort needed on your part - just do `configureStore({reducer: rootReducer})` and that's it.
