### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by kolban-google** [reduxjs/redux-devtools#1179]
I tried to install `react-json-tree` on my React 18 environment and it failed.  Do we have plans for a React 18 release?

```
$ npm i react-json-tree
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: viewer@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0 || ^17.0.0" from react-json-tree@0.16.2
npm ERR! node_modules/react-json-tree
npm ERR!   react-json-tree@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/kolban/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kolban/.npm/_logs/2022-05-30T03_52_27_323Z-debug-0.log
```

**Comment by FaberVitale** [comment]
Hi @kolban-google,

Have you tried to change the `react-json-tree` peer dependencies using [patch-package](https://www.npmjs.com/package/patch-package)?

```diff
  "peerDependencies": {
-   "@types/react": "^16.3.0 || ^17.0.0",
-    "react": "^16.3.0 || ^17.0.0"
+   "@types/react": "^16.3.0 || ^17.0.0  || ^18.0.0",
+   "react": "^16.3.0 || ^17.0.0  || ^18.0.0"
  }
```

Can you please report if it works?

@Methuselah96 we should consider a gradual migration to functional components and add react-18 as peer dependency.
We could start from smaller libs: `react-json-tree` for instance :).

**Comment by Methuselah96** [comment]
Yeah, I was hoping to upgrade the devDependencies to React 18 at the same time [here](https://github.com/reduxjs/redux-devtools/pull/1165), but there's still a few packages with old peerDependencies. I'll create a PR to just update the peerDependencies for now.
