### ISSUE TITLE
Your npm page contains a link to CRYPTO CASINOS

### ISSUE THREAD

**Issue by Zombobot1** [reduxjs/redux-devtools#1230]
On react-json-tree page there is a link that leads to crypto gambling:

<img width="161" alt="image" src="https://user-images.githubusercontent.com/48030070/191468074-5ca54835-0960-474b-b13f-f257d2098cda.png">

**Comment by Methuselah96** [comment]
Thanks for the heads-up, should be resolved by https://github.com/reduxjs/redux-devtools/pull/1231.
