### ISSUE TITLE
how can i control responsive mode ??

### ISSUE THREAD

**Issue by Eumhongin** [reduxjs/redux-devtools#1294]
how can i control responsive view??
<img width="450" alt="스크린샷 2022-12-13 오후 1 49 07" src="https://user-images.githubusercontent.com/23710025/207229266-8e470b45-8cee-450d-8778-d7c300325005.png">

i want to this layout. how can i get?
<img width="562" alt="스크린샷 2022-12-13 오후 1 54 10" src="https://user-images.githubusercontent.com/23710025/207229925-b4099edc-cccc-4685-9c7c-f163cf1fda7a.png">

[detail layout video](https://www.youtube.com/watch?v=VbPgAf3FUU8&t=1s)

**Comment by Eumhongin** [comment]
in past reponsive was auto control

**Comment by martinkrulltott** [comment]
**+1**

My Redux Devtools is also stuck in horisontal mode even though the viewport is tall and narrow (it used to be responsive and switch between horisontal and vertical automatically before). Rather than "how can I control responsive mode", I believe this is a bug with the responsiveness, you shouldn't have to do this manually...

**Comment by martinkrulltott** [comment]
Could it be related to the width change in https://github.com/reduxjs/redux-devtools/pull/1129? @FaberVitale @Methuselah96

**Comment by FaberVitale** [comment]
### Digging a bit in the code

If I recall correctly `inspector-monitor` and rtk-query-monitor` poll every X milliseconds to see if they need to use either  a horizontal or vertical layout:

- https://github.com/reduxjs/redux-devtools/blob/4c1096a3698269f5bd82bcf1a41f8bc23315441a/packages/redux-devtools-inspector-monitor/src/DevtoolsInspector.tsx#L239
-  https://github.com/reduxjs/redux-devtools/blob/4c1096a3698269f5bd82bcf1a41f8bc23315441a/packages/redux-devtools-rtk-query-monitor/src/containers/RtkQueryInspector.tsx#L91

`rtk-query-monitor` uses 600 as threshold while `inspector-monitor` uses instead 500.

---

I'll try to take a closer look at this issue during the holidays.

**Comment by Ruslancic** [comment]
Hey! Any update on this issue?

**Comment by Methuselah96** [comment]
No updates, feel free to look into it yourself.

**Comment by Eumhongin** [comment]
@Ruslancic @Methuselah96 
I use 2.17.0 version actually download from last releases.
add to chrome using custom extensions!

check this link : https://github.com/zalmoxisus/redux-devtools-extension/releases
