### ISSUE TITLE
always  crashing in my chrome

### ISSUE THREAD

**Issue by nisr19** [reduxjs/redux-devtools#1295]
<img width="1440" alt="Screenshot 2022-12-14 at 3 44 50 PM" src="https://user-images.githubusercontent.com/8463351/207568296-0a6a0cf1-b130-4485-8beb-e24b0ca5c5b3.png">

**Comment by maidangzhu** [comment]
me too

**Comment by vbifonixor** [comment]
same, crashes after I click on a dispatched action type in actions sidebar

**Comment by reganoneill** [comment]
This is happening to me as well. When I click on the 'redux' tab to open this extension, it simply doesn't load - ever.
I'm on Chrome `108.0.5359.124`
One workaround I did find is that things work perfectly fine if I just load the tool in its own window. This can be done by opening up the 'extensions' page in Chrome and selecting this app. Then hit 'details' and select 'background page' which appears under the text 'inspect views'.

**Comment by Methuselah96** [comment]
I"m having trouble reproducing. Can you right-click on in the Redux tab, press "Inspect", go to the "Console" tab, and see if there are any error messages?
