### ISSUE TITLE
Please publish latest code of @redux-devtools/remote to npm

### ISSUE THREAD

**Issue by burya4ok** [reduxjs/redux-devtools#1335]
The npm version 0.7.5 does not work correctly as it has old version of socketcluster-client.
Please publish the version from master to npm.

**Comment by Methuselah96** [comment]
Should be released in `@redux-devtools/remote@0.8.0`.

**Comment by burya4ok** [comment]
Thank you for the quick response and release!

There is another problem I found out about. With the new socket-cluster version, you are using `for-await-of` inside the code. And that does not work without the babel plugin. That should be added to the docs or the code should be rewritten.

**Comment by Methuselah96** [comment]
Can you expand on why it does not work? Seems like it's [fairly widely supported](https://caniuse.com/?search=for%20await%20of).
