### ISSUE TITLE
Firefox Addons shows 2.17.1 as the latest version

### ISSUE THREAD

**Issue by Janchu** [reduxjs/redux-devtools#1368]
The [Firefox Addons page for Redux Devtools](https://addons.mozilla.org/en-US/firefox/addon/reduxdevtools/) currently shows this as the current version information:

![Screenshot 2023-03-10 at 16 15 03](https://user-images.githubusercontent.com/17246317/224339734-717dfb57-14a9-47df-8fce-6f7c6808038f.png)

And when installed the addon info also shows the old repo as homepage:

![Screenshot 2023-03-10 at 16 15 33](https://user-images.githubusercontent.com/17246317/224340210-ac9f6fe1-d60f-4f3f-9595-f90b384cc485.png)

**Comment by Methuselah96** [comment]
Thanks for the report, Firefox seems to have disabled the 3.x versions. I am mysteriously able to re-enable 3.0.15, but not any of the other versions (including 3.0.17). The 3.0.15 should be the current version now, I'll follow-up with Firefox to figure out how to re-enable the other 3.x versions.

**Comment by erwanriou** [comment]
just to drop here saying that since this afternoon the firefox redux devtool is not working anymore in firefox. So something wrong probably happen there. 

![image](https://user-images.githubusercontent.com/30130006/224382962-7fa74550-82c2-44d8-8f21-75d5b0743891.png)

**Comment by Methuselah96** [comment]
Thanks for the report, I've disabled 3.0.15, which means we're stuck on 2.17.1 until the Firefox Add-on team gets back to us.

**Comment by erwanriou** [comment]
yes thanks, it now work after updating the version again.

**Comment by Methuselah96** [comment]
3.019 has been approved by the Firefox Add-on team and is now the latest version.
