### ISSUE TITLE
Create UMD build

### ISSUE THREAD

**Issue by ohana54** [reduxjs/redux-devtools#139]
Hi,

Continuing the discussion in #130 about AMD support here.

You (@gaearon) mentioned in #130 that you don't plan to provide an AMD version of Redux DevTools, just like there is none for redux itself.
I probably didn't explain myself correctly - I'm not looking for an "AMD" version, I just need it to be UMD compliant.
Redux is built using webpack so I can use it (and currently do) with RequireJS.
Redux DevTools is not built using webpack so I can't use it (well, I tried and failed).
I hope this explanation is better.
I'm of course willing to submit a PR that tries to add support, I just want to make sure I'm on the right track here.

Thanks for your help and patience :)

**Comment by gaearon** [comment]
Oh, I see. We can probably add a UMD build. Can you take a look at how `react-redux` repo does it with Webpack config and submit a PR doing it in a similar fashion?

**Comment by ohana54** [comment]
Sure, that was my plan :)
I'll try to make it happen during the weekend.

**Comment by ohana54** [comment]
Created #140

**Comment by gaearon** [comment]
Hey, I'm really sorry for the churn but I split the packages already.
Can you please make separate PRs to:

* this project (against the `next` branch)
* https://github.com/gaearon/redux-devtools-log-monitor
* https://github.com/gaearon/redux-devtools-dock-monitor

Sorry if that's too much, but it's hard to move forward when everything is in one place. :-(

**Comment by ohana54** [comment]
No problem, I'll take care of it
