### ISSUE TITLE
react-json-tree: support style or className props for customization

### ISSUE THREAD

**Issue by guoyunhe** [reduxjs/redux-devtools#1402]
The default style of `<JSONTree/>` component's root container has a margin. I would like to change the margin, but `<JSONTree/>` doesn't support `style` or `className` props.

**Comment by Methuselah96** [comment]
You can customize the style using [the `theme` prop](https://github.com/reduxjs/redux-devtools/tree/main/packages/react-json-tree#theming).

**Comment by guoyunhe** [comment]
@Methuselah96 sorry, I didn't get it. Examples in the doc only show how to change colors or label styles. But what I want to do is to change the margin of root container.

**Comment by Methuselah96** [comment]
You can change the style of more than just the label. The second bullet point in the docs describes how to do this:

> object that contains style objects, strings (that treated as classnames) or functions. A function is used to extend its first argument { style, className } and should return an object with the same structure. Other arguments depend on particular context (and should be described here). See [createStylingFromTheme.js](https://github.com/reduxjs/redux-devtools/blob/main/packages/react-json-tree/src/createStylingFromTheme.ts) for the list of styling object keys. Also, this object can extend base16 theme via extend property.

If you go to `createStylingFromTheme.ts` and look at the object returned by `getDefaultThemeStyling`, you can see the different styles you can customize.

In this case you probably want something like:

```js
<JSONTree
  data={data}
  theme={{
    tree: {
      margin: 0,
    },
  }}
/>
```

**Comment by guoyunhe** [comment]
Thanks! It worked.
