### ISSUE TITLE
Electron State Always Undefined

### ISSUE THREAD

**Issue by framerate** [reduxjs/redux-devtools#1407]
Hoping someone can point me in a direction. I'm working on a legacy product update and have a few older dependencies I can't currently upgrade. Might be related.... But its an electron app and I've spent about 5 hours trying everything I can find on multiple computers. Here is what I see in app:
![image](https://user-images.githubusercontent.com/74291/236641782-70ab1c1d-2864-4801-bfcc-b06927725185.png)

I initialize the tools like this with latest `electron-devtools-installer`

```  
// install extensions for development
  // debug tools
  if (isDev) {
    const extensions = [
      REDUX_DEVTOOLS,
      // 'cjmaipngmabglflfeepmdiffcijhjlbb', // Reselect Developer Tools
    ]

    extensions.forEach((p) => {
      installExtension(p, process.env.FORCE_EXTENSION_DOWNLOAD === 'true')
        .then((name) => log.info(`Added Extension:  ${name}`))
        .catch(Sentry.captureException)
    })
  }
```

Relevant logs:
```
[1] (node:9390) ExtensionLoadWarning: Warnings loading extension at /home/justin/.config/doomtrooper/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
[1]   Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
[1]   Permission 'notifications' is unknown or URL pattern is malformed.
[1]   Permission 'contextMenus' is unknown or URL pattern is malformed.
[1]
[1] 11:51:13.385 › Added Extension:  Redux DevTools
```

Relevant package.json entries:
```
"react": "^16.14.0",
    "react-dnd": "10.0.2",
    "react-dnd-html5-backend": "10.0.2",
    "react-dom": "^16.14.0",
    "react-hot-loader": "^4.13.1",
    "react-process-string": "^1.2.0",
    "react-redux": "^7.2.9",
    "react-router": "^5.3.4",
    "react-router-dom": "^5.3.4",
    "react-spring": "^8.0.27",
    "react-tooltip": "^4.2.21",
    "react-typist": "^2.0.5",
    "react-use": "^17.4.0",
    "recharts": "^1.8.6",
    "redux": "^4.2.1",
    "redux-freeze": "^0.1.7",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.4.2",
 ```
    
 I've read all github/stackoverflows I can find, I've tried installing less devtools, installing at a different time in the chain, updating electron. No matter what I do, I can't get devtools.
    
If anyone has a suggestion to help me stop pulling my hair out, I'd apprecate it <3

**Comment by framerate** [comment]
Note I saw a thread about clearing IndexDB for redux-devtools but maybe it doesn't seem to work inside electron unless someone knows more than me!

**Comment by hrivks** [comment]
Ran into this as well.
Managed to fix this by changing `"matches": [ "\u003Call_urls>" ],` to `"matches": [ "<all_urls>" ],` in the `manifest.json`.
Weird the unicode sequence doesn't work on Electron 🤷‍♂️
