### ISSUE TITLE
Open a PR for the react-json-tree package but the build is failing

### ISSUE THREAD

**Issue by lucataglia** [reduxjs/redux-devtools#1411]
I've opened this [PR](https://github.com/reduxjs/redux-devtools/pull/1410) in the `react-json-tree` package to add the `collapse/expand all` feature that I need for my project. The build is failing because of an error about the `react-base16-styling` package. On my computer I was able to solve the error by running the `yarn build:all` command from the root of the project. Running that command the lib folder of the `react-base16-styling` package was created. Could be that some commands are missing from the CI workflow ?

<img width="1078" alt="image" src="https://github.com/reduxjs/redux-devtools/assets/32895300/4cc0d599-cb98-4248-bed0-74d03ce79ef3">

**Comment by Methuselah96** [comment]
I disabled running only affected packages in CI in https://github.com/reduxjs/redux-devtools/pull/1449 so it was causing issues like this. Let me know if you have any further issues with this.
