### ISSUE TITLE
Possible to show only certain reducers from the dev tool?

### ISSUE THREAD

**Issue by OxManny-Dev** [reduxjs/redux-devtools#1435]
Is there a way to whitelist only certain reducers from showing up in the dev tools?
For example, we might have a reducer that we don't want to show the state for in dev tools, but have other reducers that we do want to see.

**Comment by markerikson** [comment]
Use the `stateSanitizer` option, and omit pieces of the state you don't want shown in the devtools UI:

```ts
const reduxDevToolsOptions: ReduxDevToolsOptions = {
  maxAge: 100,
  stateSanitizer: (state: RootState) => {
    const copy = {...state};
    delete copy.unwantedSlice;
    return copy;
  }
};
```
