### ISSUE TITLE
"export 'stateTreeSettings' (imported as 'stateTreeSettings') was not found in '@redux-devtools/app'"

### ISSUE THREAD

**Issue by moicez** [reduxjs/redux-devtools#1454]
Trying to run the redux-devtools extension in a new project. I see this error when I try to run it. Seems like a possible release issue.

![Screenshot 2023-08-14 at 1 47 15 PM](https://github.com/reduxjs/redux-devtools/assets/5168797/99df7a00-9c4b-4b4d-9d9a-f66c19f0cd32)

**Comment by Methuselah96** [comment]
It's likely that https://github.com/reduxjs/redux-devtools/pull/1264 has not been released yet. I'll try to look into that when I get a chance.

**Comment by Methuselah96** [comment]
A new version has been released, let me know if that fixes your issue.
