### ISSUE TITLE
Popup redux dev tools display is terrible

### ISSUE THREAD

**Issue by agungfir10** [reduxjs/redux-devtools#1465]
This popup view is terrible, I don't use it easy, can you fix it...

![image](https://github.com/reduxjs/redux-devtools/assets/47552952/25cffab4-d08c-404a-9326-f58027348a9c)

**Comment by Methuselah96** [comment]
I noticed this recently as well too, and I believe it looked better before. Maybe Chrome 116 broke it? PRs welcome to fix it!

**Comment by batya-bicha** [comment]
I suggest you just return min-width
![image](https://github.com/reduxjs/redux-devtools/assets/75670595/3076c4e8-e203-404c-9983-a0016cd91e01)

**Comment by Methuselah96** [comment]
I have verified that the popup would resize to a bigger width in Chrome 115 and is no longer doing so in Chrome 116.
