### ISSUE TITLE
Dev tools don't work in Firefox

### ISSUE THREAD

**Issue by apmwebdev** [reduxjs/redux-devtools#1480]
As of today, the Redux dev tools don't work in Firefox. They worked yesterday, but now they just show as blank:
![image](https://github.com/reduxjs/redux-devtools/assets/30607075/9bdc477d-8dfa-4cc3-a34f-4f54598bea37)

When opening the Redux dev tools from the address bar, they seem to work fine. Weirdly, switching the Firefox dev tools panel to the right or left side of the window instead of the bottom occasionally makes the Redux dev tools appear again. But this happens very inconsistently, and they disappear again as soon as the state of the app changes.

Troubleshooting steps I've done so far (none of which have solved the issue):
1. Disabling and re-enabling the Redux dev tools extension
2. Removing and reinstalling the Redux dev tools extension
3. Restarting Firefox and making sure it's up to date. I'm currently on version 117.0
4. Removing cached data and cookies for localhost in Firefox
5. Restarting the Redux app (via Vite)
6. Restarting my laptop (MacBook Pro with M1 chip running Mac OS 12.6.2)
7. Opening the Redux app in a private window (and making sure the extension is allowed to run in private windows)
8. Opening the Redux app in a Firefox profile with no other browser extensions except for Redux dev tools
9. Opening the Redux app in a Firefox profile with only the Redux dev tools and React dev tools
10. Opening different Redux apps, including the simple boilerplate one (shown in screenshot above)
11. Taking the previous steps in various orders

Dev tools settings:
![image](https://github.com/reduxjs/redux-devtools/assets/30607075/50750d93-570c-4f39-a50e-9b967675b7ef)
![image](https://github.com/reduxjs/redux-devtools/assets/30607075/8f6c39aa-b669-44fd-b2e0-0bd0bd5a8396)

The browser console didn't show any errors either.

The dev tools _do_ work in the latest version of Chrome.

**Comment by Methuselah96** [comment]
Thanks for the report! I have disabled the latest version on Firefox for now until I can figure out what's going on. If you remove and re-install the add-on, it should revert to the working version.

**Comment by ncoughlin** [comment]
Confirmed also not working for me on Firefox. Uninstalling and re-installing did not fix. Is working correctly on Chrome.

**Comment by Methuselah96** [comment]
@ncoughlin Sorry to hear that. Can you confirm what version is show in the "Details" section of the extension?

![image](https://github.com/reduxjs/redux-devtools/assets/693755/52c80b50-6b56-437b-941c-dbe2d5ab4b27)

**Comment by ncoughlin** [comment]
> Can you confirm what version is show in the "Details" section of the extension?
> 


3.0.19

**Comment by Methuselah96** [comment]
Does anything render for you in the "Redux" tab, or is it just a gray screen? Does the popup work at all for you?

**Comment by apmwebdev** [comment]
Just as an additional data point here, rolling back to 3.0.19 immediately fixed the problem for me. I wonder if we're dealing with two separate issues? Appreciate your help with this @Methuselah96.

**Comment by marioGMIT** [comment]
i'm able to reproduce the issue in firefox and chrome.
I have the feeling that the plugin deploy the redux devtool dashboard in a new firefox's window?
Double click on the gray background -> Redux devtools -> select any option. It pops up a new windows with the dashboard.

**Comment by Methuselah96** [comment]
I this is fixed by https://github.com/reduxjs/redux-devtools/pull/1486. 🤞
