### ISSUE TITLE
No longer work in Chrome Incognito

### ISSUE THREAD

**Issue by carltonstith** [reduxjs/redux-devtools#1481]
As of today, the Redux dev tools don't work in Chrome (Version 116.0.5845.140 (Official Build) (arm64)) Incognito. This worked yesterday, but now it just shows blank. I've tried removing and reinstalling the extension. I have 2 Macbook Pro's and this bug occurs on both machines.

**Comment by toddmcbrearty** [comment]
+ 1

**Comment by toddmcbrearty** [comment]
I have the same issue without using incognito. It flashes the screen for a moment then it's just blank.

**Comment by Baku452** [comment]
I have the same issue using Firefox

**Comment by huestack** [comment]
- Version 116.0.5845.179 (Official Build, ungoogled-chromium) (64-bit)

![Screenshot_20230912_171303](https://github.com/reduxjs/redux-devtools/assets/11208563/195c710c-a192-4fa5-9bb2-bbf10e14df7c)

**Comment by antrant** [comment]
I got the same error

**Comment by Methuselah96** [comment]
Thanks for the report, I've found [a fix](https://github.com/reduxjs/redux-devtools/pull/1486) and will try to get it released ASAP.
