### ISSUE TITLE
Dispatch text area disabled

### ISSUE THREAD

**Issue by dariomalfatti-centropaghe** [reduxjs/redux-devtools#1489]
After updating the extension to the version 3.1.2 with Chrome 117.0.5938.63 the text area to manually dispatch an action is always disabled. With Firefox it works fine.

**Comment by mattr-cb** [comment]
Same issue in Chromium 116.0.5845.110.

Additionally, the textareas for custom actions with dynamic payloads are broken.

As a workaround, you can dispatch actions in the dev tools console like this:

```
window.REDUX_STORE.dispatch({ type: 'ACTION_NAME' });
```

**Comment by Methuselah96** [comment]
This should be fixed by https://github.com/reduxjs/redux-devtools/pull/1491, will try to get it released ASAP.
