### ISSUE TITLE
Raw tab in the inspector is blank with an extra large scrollable area

### ISSUE THREAD

**Issue by chrisisonline** [reduxjs/redux-devtools#1490]
Using v3.1.2 with Chrome Version 117.0.5938.63 (Official Build) (64-bit)

The Tree and Chart views are working, it seems that only the Raw tab is affected

**Comment by Methuselah96** [comment]
This should be fixed by https://github.com/reduxjs/redux-devtools/pull/1491, will try to get it released ASAP.
