### ISSUE TITLE
immer enableMapSet

### ISSUE THREAD

**Issue by mharj** [reduxjs/redux-devtools#1522]
Hi devs,
I'm using Map and Set on redux and devtools currently just shows {} as state values.
Any chance to extract Map and Set instances with Array.from() to devtools UI? or have dedicated Map and Set structures

Br. Marko

**Comment by markerikson** [comment]
We specifically advise _against_ using Maps or Sets inside Redux state:

- https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions
