### ISSUE TITLE
@opentelemetry/context-zone Maximum call stack size exceeded occurs when the Redux Tool Chrome Extension is enabled for Next v13.5.4

### ISSUE THREAD

**Issue by WeirShi** [reduxjs/redux-devtools#1524]
This is relevant information, can you help to look at it.
[Question](https://github.com/open-telemetry/opentelemetry-js/issues/4213)

**Comment by markerikson** [comment]
This is likely a Next-specific issue tied to their use of the Redux DevTools:

- https://github.com/vercel/next.js/blob/ffdfd33251165d8b2f092568c8e4e5f08c71a636/packages/next/src/client/components/use-reducer-with-devtools.ts#L12
