### ISSUE TITLE
Remove NPM from Design System

### ISSUE THREAD

**Issue by Flobis** [reduxjs/redux-devtools#1609]
NPM a été utilisé pour régler un souci de build dû à des packages non compatibles.
Actions à mettre en place:
  vérifier si on peut remettre yarn
  sinon
  uniformiser le build et les différentes images gcp afin d'être consistant

**Comment by Methuselah96** [comment]
Hello!

Unless I'm mistaken, this issue is not for redux-devtools (we are currently using pnpm as our package manager).
