### ISSUE TITLE
npm i && npm run build:firefox failed

### ISSUE THREAD

**Issue by doczkal** [reduxjs/redux-devtools#1617]
I am trying to build for Firefox https://github.com/reduxjs/redux-devtools/tree/main/extension#2-for-firefox

> npm i

shows warnings but seems OK

> npm run

Scripts available in undefined via `npm run-script`:
  format
    prettier --write .
  format:check
    prettier --check .
  build:all
    nx run-many --target=build --all --parallel=1
  lint:all
    nx run-many --target=lint --all --parallel=1
  test:all
    nx run-many --target=test --all --parallel=1
  clean:all
    nx run-many --target=clean --all --parallel=1
  release
    pnpm build:all && changeset publish

> npm run build:firefox
npm ERR! Missing script: "build:firefox"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
npm ERR! A complete log of this run can be found in: ~/.npm/_logs/2024-02-27T07_52_23_574Z-debug-0.log

Steps to reproduce

1. git clone https://github.com/reduxjs/redux-devtools.git
2. cd redux-devtools
3. npm i && npm run build:firefox

am I missing something?
I also tried the npm commands in "extension" sub-directory with similar results. npm run build:all doesn't work either.

OS:
CentOS Linux release 7.9.2009 (Core)

> node --version

v20.11.0

> npm --version

10.2.4

**Comment by Methuselah96** [comment]
Sorry for the confusion, the READMEs were created before the projects were combined into a monorepo. Running `pnpm install` and `pnpm run build:all` in the redux-devtools directory should work. The output for Firefox will be in `extension/firefox/dist/`.

Let me know if I can help with anything else.
