### ISSUE TITLE
May soon no longer be supported in Chrome

### ISSUE THREAD

**Issue by dhzhme** [reduxjs/redux-devtools#1704]
Hello, guys. I noticed this phenomenon on my Chrome extension page, can anyone tell me what happened? Can we still use this plugin?

![CleanShot_2024-08-02_23 22 09@2x](https://github.com/user-attachments/assets/dac28e08-7c1f-4e2b-942c-c88a8e648d14)
![CleanShot_2024-08-02_23 22 21@2x](https://github.com/user-attachments/assets/c4c4e668-6a8d-474e-b93d-fcd079bba71e)

**Comment by Methuselah96** [comment]
Redux DevTools currently uses Manifest V2 which will [soon be unsupported](https://developer.chrome.com/blog/resuming-the-transition-to-mv3/). We are working on [the upgrade to Manifest V3](https://github.com/reduxjs/redux-devtools/issues/1037), but it is not a trivial upgrade and this project is maintained during my free time. I hope to complete the upgrade within the next few weeks, but it is still unclear when support for Manifest V2 will actually end, so any information on that would be greatly appreciated.

**Comment by dhzhme** [comment]
> Redux DevTools currently uses Manifest V2 which will [soon be unsupported](https://developer.chrome.com/blog/resuming-the-transition-to-mv3/). We are working on [the upgrade to Manifest V3](https://github.com/reduxjs/redux-devtools/issues/1037), but it is not a trivial upgrade and this project is maintained during my free time. I hope to complete the upgrade within the next few weeks, but it is still unclear when support for Manifest V2 will actually end, so any information on that would be greatly appreciated.

That's it, I understand, thank you for your answer!
