### ISSUE TITLE
Manifest V3 Progress

### ISSUE THREAD

**Issue by Methuselah96** [reduxjs/redux-devtools#1705]
This issue tracks the work on [upgrading to Manifest V3](https://github.com/reduxjs/redux-devtools/issues/1037).

- [x] Remove direct access of monitors to background page Redux store (addressed in https://github.com/reduxjs/redux-devtools/pull/1714)
  - The primary Redux DevTools window accesses [the background page](https://github.com/reduxjs/redux-devtools/blob/main/extension/src/window/index.tsx#L12) and takes advantage of the fact that variables could be directly accessed through the `window` variable. This is [no longer possible in MV3](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers#differences-with-sws), so we'll need to [rely on message passing](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers#move-dom-and-window) instead. This unfortunately means that the Redux DevTools will be slower by undoing the performance gains that were made in https://github.com/zalmoxisus/redux-devtools-extension/pull/580.
- [x] https://github.com/reduxjs/redux-devtools/pull/1706
  - Chrome has a maximum message length. We work around this when passing messages between the content script and background page by [splitting messages](https://github.com/zalmoxisus/redux-devtools-extension/pull/582). Since we now need to rely on message passing between the background page and the monitors, we need to add message splitting there as well.
- [ ] Remove Redux store from background page (partially addressed by https://github.com/reduxjs/redux-devtools/pull/1714)
  - Background pages have been [replaced with service workers](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers) which are terminated when not in use. This means that we can no longer rely on keeping a Redux store in-memory in the service worker. This means that we either need to store the Redux state in localStorage and recreate the store each time the service worker is created or make it so that the service worker does not need the Redux store at all.
- [x] Update page script code injection (addressed by https://github.com/reduxjs/redux-devtools/pull/1714)
  - MV3 no longer allows injecting a script element into the page, so we'll have to adjust our strategy for injecting the page script. Looking at how React DevTools [adjusted to this](https://github.com/facebook/react/pull/25145) for inspiration.
- [ ] Make sure Firefox still works
- [x] Fix E2E tests

More work will be added to this list as needed.

**Comment by ryota-murakami** [comment]
@Methuselah96 Thank you for your work to support V3 manifest!
I thought support V3 require only adjust `manifest.json` format, but seems like need many implementation modify by V3 restriction. 😓

**Comment by samselfridge-cnc** [comment]
Is this why ReduxDevTools was removed from chrome and I had to manually add it back in and I'm seeing this message on the chrome store?
![image](https://github.com/user-attachments/assets/2f69caae-9f76-4c92-8a2d-ce56b5ddd201)

**Comment by Methuselah96** [comment]
I am not aware of it being automatically removed from Chrome, but that could be. It is the reason for the message, yes.

**Comment by westerntc-gtg** [comment]
> I am not aware of it being automatically removed from Chrome, but that could be. It is the reason for the message in the Chrome Web Store, yes.

I know there is talk that some of these would jsut suddenly become disabled.  And only later removed.  I play with multiple chrome instance profiles so I can keep project testing separate, and routinely see them disappear though.  It might not have anything to do with the coming 'disabling' and removal.

**Comment by il-darin** [comment]
In Chrome canary, the extension now just outright crashes :-/

**Comment by Methuselah96** [comment]
What version of the extension do you have installed? I've started releasing 3.2.0 which uses MV3, but paused the rollout due to [some issues](https://github.com/reduxjs/redux-devtools/issues/1732) that need investigation.

**Comment by il-darin** [comment]
this is still with 3.1.10.  I need to look into how to install 3.2 on canary it seems

**Comment by il-darin** [comment]
> [edit] just removing and re-adding the extension upgraded to the latest. It no longer crashes, however now the pane is blank 😔

likely a dupe of #1733
