### ISSUE TITLE
One of the last updates causes lags on the website

### ISSUE THREAD

**Issue by uulaal** [reduxjs/redux-devtools#1754]
2 days ago app.gather.town started lagging a lot in my Chrome. Today I found out that disabling the extension fixes the problem. It seems like some of the latest updates causes these lags, because I've had Redux DevTools permanently enabled for years and I've never experienced such troubles.

Windows 11
Chrome Version 128.0.6613.120 (Official Build) (64-bit)

**Comment by Methuselah96** [comment]
What version do you have installed? We've released some fixes to[ a related issue report](https://github.com/reduxjs/redux-devtools/issues/1732) recently.

**Comment by uulaal** [comment]
Thanks for the update! I just tried installing 3.2.4 and now everything works fine.

The problems I've encountered were on 3.2.0.
