### ISSUE TITLE
Vue warning if redux store and devTools are present

### ISSUE THREAD

**Issue by theSilverFisch** [reduxjs/redux-devtools#1774]
After updating to vue 3.5 on a websystem we've build, using a redux store and vue 3 we encountered that having the devTools enabled will lead to those vue warnings until the max callstack is exeeded:
![image](https://github.com/user-attachments/assets/958af04d-d277-4a97-907b-e36e39e4ed2e)

Once I disable the reduxDevTools the warning disappears

**Comment by Methuselah96** [comment]
Does your Redux state or actions contain Vue components?

**Comment by theSilverFisch** [comment]
No, but my vue components do use the redux store and trigger dispatches as well as use subscribers

**Comment by markerikson** [comment]
@theSilverFisch can you show _how_ you're trying to use the Redux store in those components?  

Possibly related, note that we just released a new official Vue+Redux integration, and you might want to look at using that:

- https://github.com/reduxjs/vue-redux


FWIW the Redux DevTools should only be interacting with the Redux store and its state, so I would tend to suspect that somehow a Vue component reference is indeed getting inside the Redux state.

**Comment by theSilverFisch** [comment]
We use vuetify and usually just dispatch "normal" payloads such as objects, arrays, strings and numbers into the store like so
``<template>
    [...]
    <v-btn
      variant="outlined"
      color="primary"
      @click="submitForm"
    >
      submit
    </v-btn>
</template>
<script setup>
[...]
const $store = inject('$store")
const form = ref({})
const submitForm=()=>{
      $store.dispatch({
        type: "data/add",
        payload: {
              formData: form.value
        },
      })
}

</script>
``

**Comment by markerikson** [comment]
Hmm. Not sure there's much we can do here without a reproduction to look at.

**Comment by theSilverFisch** [comment]
we are currently investigating the issue further. The warning and the maxcall stack are printed from a js file within the devTools chrome extension. But we also decorate actions. I will report once we have further findings. If it is actually a extension issue I'll provide a fiddle or test project
