### ISSUE TITLE
Suggestion: More verbose error handling for actions

### ISSUE THREAD

**Issue by michaelgmcd** [reduxjs/redux-devtools#246]
I can implement something for you if you'd like and make a PR, I just thought I would get your opinion first. I think it would be useful to improve the error handling here. In my project, I forgot to register a middleware, so this was being thrown for one of my actions that the middleware normally handles. I was able to figure it out by editting `instrument.js` and logging the action that caused the error.

``` js
if (typeof action.type === 'undefined') {
  console.log(action);
  throw new Error('Actions may not have an undefined "type" property. ' + 'Have you misspelled a constant?');
}
```

Again, I'm not sure what the best way to handle this would be, just bringing this up.

**Comment by SpaceHexagon** [comment]
I'm not getting any error details.. have to rely on redux logger middleware for that
