### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON when redux-form

### ISSUE THREAD

**Issue by juanpasolano** [reduxjs/redux-devtools#262]
Hi thanks for the awesome project.
Just to report an issue when having redux-devtools and redux-form. 
When you implement the [simplest example in redux-form](https://github.com/erikras/redux-form/blob/master/docs/GettingStarted.md) you get the error `Uncaught TypeError: Converting circular structure to JSON`.

**Comment by zalmoxisus** [comment]
Probably you use `persistState`, don't you? Does it happen without `debug_session` set?

**Comment by juanpasolano** [comment]
I have checked and apparently I don't have a `persistState`

**Comment by gaearon** [comment]
Can you please write the stack trace?

**Comment by zalmoxisus** [comment]
Actually, it's easy to reproduce, just by having circular references in states, which throughs in [`JSON.stringify`](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js#L51). Don't know about `redux-form`, but I used to have this problem with redux-router, which uses circular references.

In chrome extension we use [`jsan`](https://github.com/kolodny/jsan), which handle circular references, and as it tries first to do `JSON.stringify`, there's no performance impact.

Will send a PR with tests in a couple of days.

**Comment by gaearon** [comment]
:+1: 

In general having circular references is not very good by itself. cc @erikras

**Comment by juanpasolano** [comment]
Do you guys still need the stack trace?

**Comment by erikras** [comment]
Thanks for the cc. This is news to me. Yes, @juanpasolano, the stack trace would be nice.
