### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

### ISSUE THREAD

**Issue by CurtisHumphrey** [reduxjs/redux-devtools#297]
I'm now getting this message: "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead." and because of it actions are taking seconds to process.  This is related to localStorage. Any ideas?

**Comment by zalmoxisus** [comment]
Could you provide the stack trace? I don't see it being used here.

**Comment by CurtisHumphrey** [comment]
I think it is related to exceeding 10MB in the history.  When it happens to me again today I'll post more.

**Comment by ananddodia** [comment]
I am also facing same issue. Please update if any solution found.

**Comment by zalmoxisus** [comment]
@ananddodia, you can limit the data to be stored by adding [`maxAge` parameter](https://github.com/zalmoxisus/redux-devtools-instrument#api) as following:

``` js
const enhancer = compose(
  applyMiddleware(d1, d2, d3),
  DevTools.instrument({ maxAge: 50 }),
  persistState(getDebugSessionKey())
);
```
