### ISSUE TITLE
Record and replay events (import/export) like redux-vcr

### ISSUE THREAD

**Issue by StevenACoffman** [reduxjs/redux-devtools#326]
So [redux-vcr](https://github.com/joshwcomeau/redux-vcr) allows people to record and replay events, but the developer feels like there's a lot of overlap with redux-devtools in joshwcomeau/redux-vcr#1 and has thought about integrating the functionality into or sharing it with redux-devtools somewhere.

I looked at it a bit, but I found the effort very daunting. I'm not even sure where this would go. redux-devtools-log-monitor? Anyone familiar who could help out?

**Comment by zalmoxisus** [comment]
It can be used as monitor for navigating the stored logs, while the client side (included in production) should remain stand-alone.

If you want to try, you can take [`remotedev-slider` monitor](https://github.com/zalmoxisus/remotedev-slider/blob/master/src/index.js) as an example. If not, I'll try to integrate it when we'll have Redux DevTools Extension 3.0.

**Comment by StevenACoffman** [comment]
Whew. I took a stab at it, but completely lost the plot. I'm going to have to leave this for someone who knows which end is up. Sorry.
