### ISSUE TITLE
How to know if Redux Devtool window is already opened

### ISSUE THREAD

**Issue by tangentlin** [reduxjs/redux-devtools#339]
We have hot reload turned on for our application, at times the statement of opening Redux Devtool gets triggered.  When it happens, the DevTool steals the focus.  This can get annoying when developer is in the middle of writing and saving code, and the action of saving would trigger the build which subsequently opens the Redux DevTool.

I wonder if there is a way to know if the Redux DevTool is already open, so we can open the devtool when necessary.

**Comment by zalmoxisus** [comment]
Could you please show how you create the store and integrate Redux DevTools? Are you using browser extension? If so, I suspect you're calling [`window.__REDUX_DEVTOOLS_EXTENSION__.open`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#open), which you shouldn't do.

**Comment by tangentlin** [comment]
Yes, I have the Chrome browser extension installed.  Below is the relevant code.

```
if (window.__REDUX_DEVTOOLS_EXTENSION__) {
    enhancers.push(window.__REDUX_DEVTOOLS_EXTENSION__());
    window.__REDUX_DEVTOOLS_EXTENSION__.open('panel');
}
```

**Comment by zalmoxisus** [comment]
As described in [the docs](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#open), "this should be conditional (usually you don't need to open extension's window automatically)".

My suggestion is to remove `window.__REDUX_DEVTOOLS_EXTENSION__.open('panel');` and open the window manually when needed (from context menu or by clicking the extension's icon). Also you can use from Chrome devpanel.

We could add a second argument, not to focus the window, so you would call it like `window.__REDUX_DEVTOOLS_EXTENSION__.open('panel', false)`, but I don't see the real use case for that (unless you add more details why it is useful). My opinion is that auto opening the extension's window is bad UX.
