### ISSUE TITLE
Export Date state then import back convert into Strings

### ISSUE THREAD

**Issue by holyman2k** [reduxjs/redux-devtools#340]
When export a state contains a date object, then import the same state back, the object is stored as string instead of date

**Comment by JemarJones** [comment]
I'm experiencing this issue when my dates are meant to be moment objects, but just come back as strings and then none of the state loads.

**Comment by zalmoxisus** [comment]
@holyman2k, @JemarJones in order the extension to handle unserializable  by JSON.stringify data (like dates, regexes, undefined, error objects, symbols and functions) just set `serialize` parameter to `true`:
```js
const store = Redux.createStore(reducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__({
   serialize: true
}));
```

See [Troubleshooting](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md) and [API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize) for more details.

Note that [the extension](https://github.com/zalmoxisus/redux-devtools-extension) implementation are completely different from the repository you were filing the issue, thus the confusion.

**Comment by JemarJones** [comment]
Oh, and here i was thinking it didn't have anything to do with the extension 😅. Also i seem to have something slightly different than what you have there, i have:

```
const store = createStore(
  appReducer,
  compose(
    // The logger MUST be last (other than DevTools)
    applyMiddleware(routerMiddleware(browserHistory), thunk, logger),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )
);
```

Should i just do:

```
const store = createStore(
  appReducer,
  compose(
    // The logger MUST be last (other than DevTools)
    applyMiddleware(routerMiddleware(browserHistory), thunk, logger),
    window.devToolsExtension ? window.devToolsExtension({
        serialize: true
    }) : f => f
  )
);
```
?

**Comment by zalmoxisus** [comment]
@JemarJones yes, your snippet looks good to me. Just keep in mind that [`window.devToolsExtension` will be deprecated in favour of `window.__REDUX_DEVTOOLS_EXTENSION__`](https://github.com/zalmoxisus/redux-devtools-extension/issues/220).
