### ISSUE TITLE
Should disabling @@router/LOCATION_CHANGE go back in history?

### ISSUE THREAD

**Issue by egorovli** [reduxjs/redux-devtools#357]
Not an issue, but rather a question. Disabling actions works fine. However, disabling `@@router/LOCATION_CHANGE` does nothing (no transition to the previous route). I can't figure out whether it's an intended behavior or I'm missing something.

**Comment by evandavis** [comment]
You need `react-router-redux` to get time-travel to follow router actions.

**Comment by egorovli** [comment]
@evandavis I'm using that one, too, `5.0.0-alpha.6`, for `ConnectedRouter`. As a reducer I use my own function to work with `Immutable` (or at least I think it should work this way):
### ./modules/router.js

```javascript
import { fromJS } from 'immutable';
import { handleActions } from 'redux-actions';

// Actions
const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

// Initial state
const initialState = fromJS({
  location: null
});

// Reducer
export default handleActions({
  [LOCATION_CHANGE]: (state, { payload }) =>
    state.set('location', fromJS(payload))
}, initialState);
```
