### ISSUE TITLE
When storing a File object in the store, redux-devtools shows an empty object instead of the File object

### ISSUE THREAD

**Issue by alp82** [reduxjs/redux-devtools#360]
The state diff shows:

```
[
  {}
]
```

When outputting the contents of the store in the console, the file object correctly shows up. Therefore it's only a display issue in the extension.

**Comment by superburrito** [comment]
Same problem surfaces with FileList objects

**Comment by c0d0g3n** [comment]
I'm having the same issue with error objects and in every* view (even raw). (Quite annoying when you're dealing with [FSA's](https://github.com/acdlite/flux-standard-action).) Also `Infinity` is shown as `null`.

I suspect this is intended (although imo not well thought out) behavior. I'm using the chrome browser extension if that helps.

(*I did not actually verify every view, but I remember this issue showing op in multiple places. There's probably a central module responsible for this behavior.)

**Comment by fczuardi** [comment]
It also display WebSocket instances as ``{}``

**Comment by zalmoxisus** [comment]
The extension has an option to [serialize](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize) types like `Infinity` (which is converted to `null` by `JSON.stringify`). For cases like files, you either add your custom replacer with `__serializedType__` like in [the example](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize) or [sanitize](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) it to specific data to show.

**Comment by bakajvo** [comment]
Same with Error instance :(
