### ISSUE TITLE
Typecasting throwing bad diffs

### ISSUE THREAD

**Issue by jeremybalog** [reduxjs/redux-devtools#367]
Consider:

```
console.info(typeof getState().search.listings[1].pricing.price_avg)
dispatch( setEbayLoading( true ) )
console.info(typeof getState().search.listings[1].pricing.price_avg)
```

The output of both console.info values are `number`, but DevTools shows the values are improperly getting mutated from string => number when it should be number => number and no diff occurred:

![image](https://user-images.githubusercontent.com/12202407/26941161-7b6cd3aa-4c4b-11e7-813a-1191f3203135.png)

The previous action was setting the `listings` array which is where the bug might be--setting the listings deep assigned objects to the proper typeof.  No matter what action comes after the setting the listings, the DevTools is showing the typecasting from string to number erroneously.

**Comment by zalmoxisus** [comment]
There was a regression on `jsan` part with serialization. It's fixed already in last versions. Feel free to reopen if it still persists.
