### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by daryn-k** [reduxjs/redux-devtools#371]
File: redux-devtools/examples/counter/src/store/configureStore.dev.js

const enhancer = compose(
  applyMiddleware(thunk),
  DevTools.instrument(),
  persistState(
    window.location.href.match(
      /[?&]debug_session=([^&#]+)\b/
    )
  )
);

Window is not defined

It's stupid for server-side rendering app!

**Comment by zalmoxisus** [comment]
I think you can just add `typeof window !== 'undefined'` of there are no other issues on SSR the component.

**Comment by jhenriquevissotto** [comment]
I have the same problem.

**Comment by Methuselah96** [comment]
@jhenriquevissotto Did you try adding `typeof window !== 'undefined'`?
