### ISSUE TITLE
Dev tools do not show pieces of state that are undefined even though they are present

### ISSUE THREAD

**Issue by lagerdeveloper** [reduxjs/redux-devtools#375]

**Comment by noahzgordon** [comment]
@lagerdeveloper, assuming you mean object properties with values of `undefined`? I just tested this out with the TodoMVC app and it doesn't appear to be the case.

![screen shot 2018-01-08 at 7 11 43 pm](https://user-images.githubusercontent.com/7379855/34698762-d6d97b08-f4a7-11e7-9310-3a55b414b46a.png)

**Comment by zalmoxisus** [comment]
Yes, I guess that was about Chrome Extension. You need to add [`serialize` option](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize0, otherwise JSON.stringify loses it.
