### ISSUE TITLE
How do I uninstall redux-devtools from an Electron app?

### ISSUE THREAD

**Issue by aguynamedben** [reduxjs/redux-devtools#376]
Hi. I began using `redux-devtools` through the `electron-react-boilerplate` project, which by default uses `electron-devtools-installer` to install `redux-devtools`. I believe I'm suffering from the keyUp performance issues mentioned in https://github.com/gaearon/redux-devtools/pull/133.

I'm not currently relying on `redux-devtools` very heavily, so for now I'd just like to completely remove `redux-devtools` from my Electron application. How do I do that?

I've commented out `redux-devtools` from being installed:
```js
const installExtensions = async () => {
  const installer = require('electron-devtools-installer');
  const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
  const extensions = [
    'REACT_DEVELOPER_TOOLS',
    // Don't use redux-devtools until this performance problem is fixed: https://github.com/gaearon/redux-devtools/issues/81
    // Also see configureStore.dev.js
    //'REDUX_DEVTOOLS'
  ];

  return Promise
    .all(extensions.map(name => installer.default(installer[name], forceDownload)))
    .catch(console.log);
};
```

I don't know if it matters, but I also uninstalled the Redux Devtools extension from my main Chrome browser. I also rm -rf'ed the corresponding directory in `~/Library/Application\ Support/Google/Chrome/Default/Extensions/`.

But when I run my Electron app, in the Chrome Devtools I still see the Redux tab, and using the text input of my app and Chrome Devtools is still very slow and laggy.

How do I uninstall `redux-devtools` from an Electron app? I Googled and found something around removing files from the `userData` directory, but I can't figure out where that is.

**Comment by SAudelOG** [comment]
once it get installed once it will be forever unless you explicitly removes the extension
check here https://github.com/electron/electron/blob/master/docs/api/browser-window.md#browserwindowremovedevtoolsextensionname

**Comment by m4major** [comment]
use it after electron ready (app.on('ready'....)
BrowserWindow.removeDevToolsExtension('React Developer Tools');
