### ISSUE TITLE
Does this supports Chrome extension?

### ISSUE THREAD

**Issue by JHanLu** [reduxjs/redux-devtools#382]
I am wrting a Chrome Extension page, and when I open the Redux DevTools Panel, there's noting in it. So I was wandering if there is anthoer standalone version for Chrome Extension?

**Comment by herodrigues** [comment]
You just need to follow the walkthrough guide:

https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md

I recommend you to render the Redux DevTools container in a separate window.

**Comment by Methuselah96** [comment]
@JHanLu I'm not really sure I understand your question. If this is still relevant, please fell free to clarify and I'll re-open this issue.
