### ISSUE TITLE
About using applyMiddleware

### ISSUE THREAD

**Issue by Leotw** [reduxjs/redux-devtools#388]
well, I created a tiny thunk named `api.js` which is in `middleware` directory,  the request function was based on a `Promise` object and return a new promise object,  like this:

<img width="447" alt="wx20171128-171019 2x" src="https://user-images.githubusercontent.com/12053096/33311214-0f14c194-d45f-11e7-906b-8f8232b6bc46.png">

And the `api.js` was composed in `applyMiddleware`, like this:

<img width="469" alt="wx20171128-171622 2x" src="https://user-images.githubusercontent.com/12053096/33311470-dd511076-d45f-11e7-802c-d7ca49b6e431.png">

In my containers's `action.js`, I can write as follows:

<img width="700" alt="wx20171128-171823 2x" src="https://user-images.githubusercontent.com/12053096/33311593-3e90f9b4-d460-11e7-8911-3a75e2037743.png">

However, may I get the `_promise` instance  which in `api.js`? cause I wanna use `await/async` based on this `_promise` instance.

**Comment by zalmoxisus** [comment]
Looks like it's not related to the current repository.
