### ISSUE TITLE
Moving redux-devtools ecosystem to an org

### ISSUE THREAD

**Issue by kachkaev** [reduxjs/redux-devtools#394]
Hi @gaearon,

I'm curious what you think about moving redux-devtools repos into a dedicated group, say https://github.com/redux-devtools. This idea has been discussed between @zalmoxisus, @romseguy and me here:
* https://github.com/romseguy/d3-state-visualizer/pull/13
* https://github.com/zalmoxisus/redux-devtools-extension/issues/269

Both @zalmoxisus and @romseguy seem to support this move as you can see in the comments, however, this might take some time given that they are not visiting github very often these days. The migration of the repos may remove some pressure from the original authors and also help PRs like https://github.com/romseguy/d3-state-visualizer/pull/13 quicker propagate to the end users (the one I'm mentioning is over six months old).

If you're happy to move the main `redux-devtools` repo into a new org, at least these other repos could go there as well:
* https://github.com/romseguy/d3-state-visualizer
* https://github.com/romseguy/redux-store-visualizer
* https://github.com/romseguy/redux-devtools-chart-monitor
* https://github.com/zalmoxisus/redux-devtools-extension
* https://github.com/zalmoxisus/remote-redux-devtools
* https://github.com/zalmoxisus/redux-devtools-instrument

BTW I'm not asking to become a part of the new group myself – I haven't contributed enough and I'm not sure I can take a long-term responsibility of a maintainer. However, I guess that a common place for the sister repos will help the community move the redux-devtools ecosystem forward! 🚀 

WDYT?

**Comment by kachkaev** [comment]
ping @gaearon

**Comment by kachkaev** [comment]
ping @gaearon

**Comment by kachkaev** [comment]
ping @gaearon 😞

**Comment by montogeek** [comment]
Can't @zalmoxisus do it?

**Comment by kachkaev** [comment]
@montogeek I guess he can't — he's not the owner of this repo.

**Comment by gaearon** [comment]
I took https://github.com/reduxjs early on just in case. It’s mine.

Wanna move Redux there?

**Comment by timdorr** [comment]
Ah, cool! Let's do that. 

Can you add me to the org as an admin so I can do the transfer myself? I'll want to coordinate some things (URLs in package.json, gitbook setup, etc) and schedule it so it happens without too much issue or breakages.

**Comment by gaearon** [comment]
@timdorr Added you

**Comment by kachkaev** [comment]
👏 @gaearon @timdorr! 

@timdorr @zalmoxisus could you add @timdorr to your repos so that he could move them? Or instead, could you be added to https://github.com/reduxjs to move the repos yourself?

**Comment by gaearon** [comment]
LMK when the org is set up, and I can transfer my repos to it

**Comment by timdorr** [comment]
Can you make me an admin/owner/whatever? I'll click the right buttons to make it happen.

**Comment by gaearon** [comment]
Transferred repo to you

**Comment by timdorr** [comment]
Can you make me an org admin too? I'll get it over to the org and invite in the relevant folks.

**Comment by gaearon** [comment]
should be done

**Comment by timdorr** [comment]
OK, moved it over and invited @zalmoxisus in to the Dev Tools team

**Comment by timdorr** [comment]
Can @zalmoxisus and @romseguy request transfers of those repos into the @reduxjs org? I've added them both to the Dev Tools team, and I will make sure they maintain admin access to those repos.

**Comment by timdorr** [comment]
BTW, you do this from the repo settings here:

![screen shot 2018-04-20 at 11 49 49 am](https://user-images.githubusercontent.com/17882/39061028-02e94abe-4491-11e8-9e47-073ebd8aa7f0.png)

![screen shot 2018-04-20 at 11 50 03 am](https://user-images.githubusercontent.com/17882/39061033-052a0d04-4491-11e8-8ff4-8d5a9ed1cebb.png)

**Comment by romseguy** [comment]
@timdorr I approved your org invitation but the button "I understand, transfer this repository." remains disabled so I can't submit the form above... Any clue why?

**Comment by romseguy** [comment]
Submitting the form above I get " Sign out
You don’t have the permission to create repositories on reduxjs”

**Comment by timdorr** [comment]
Oops, had that set wrong. Just checked the right box, so give it another go!

**Comment by gaearon** [comment]
@timdorr Do you mind if I also transfer `redux-thunk`?

**Comment by timdorr** [comment]
Not at all. Anything Redux-y that you have under your personal account that you want to transfer over is totally fine.

**Comment by kachkaev** [comment]
@romseguy thanks for moving [redux-devtools-chart-monitor](https://github.com/reduxjs/redux-devtools-chart-monitor)! Do you also mind migrating these two repos?
* https://github.com/romseguy/d3-state-visualizer
* https://github.com/romseguy/redux-store-visualizer

I have a pretty selfish reason for asking, which is https://github.com/romseguy/d3-state-visualizer/pull/13 😅

**Comment by romseguy** [comment]
I moved d3-state-visualizer.

redux-store-visualizer is just a demo of redux-devtools-chart-monitor, it could be deleted.

**Comment by kachkaev** [comment]
Big thanks @romseguy! Also what is your view on npm publishing access for https://www.npmjs.com/package/d3-state-visualizer?

**Comment by timdorr** [comment]
I made @romseguy a maintainer of the Dev Tools team in the org, so he can add anyone else that should be included in there. I'll do the same for @zalmoxisus as soon as he accepts the invite :)

**Comment by romseguy** [comment]
@kachkaev you should now have push access to d3-state-visualizer on both npm and github

**Comment by SavePointSam** [comment]
Shouldn't this be closed now?

**Comment by zalmoxisus** [comment]
@romseguy we'll also need access to:
- [`map2tree`](https://github.com/romseguy/map2tree) to add [support for ES6 Map](https://github.com/zalmoxisus/redux-devtools-extension/issues/581)
- [`d3tooltip`](https://github.com/romseguy/d3tooltip) for serializing custom types and [HTML entities](https://github.com/zalmoxisus/redux-devtools-extension/issues/462).

If we go with monorepo, no need to move everything to the org, just I'll need push access to npm (including the other 2 packages already moved to this org) and, after we merge the code, to add in description that it was moved to [reduxjs/redux-devtools](https://github.com/reduxjs/redux-devtools) monorepo. I still have many critical issues to address, before starting that, so no rush with that.

I'll also add @kachkaev as a collaborator to this repository. If we go with monorepo then probably should transfer those repositories back (instead of keeping them orphaned in the org)? We could maintain those outside if you want.
