### ISSUE TITLE
How to use Redex DevTools to replace the console.log operation and the debugger?

### ISSUE THREAD

**Issue by m26597** [reduxjs/redux-devtools#405]
I've learned the Redex DevTools that could make the dev process easier, but I don't know some using method of replacing the console.log operation and debuging with the breakpoing. Is there some detail handbook ? I've read the offical guide but don't receive much. Please help me, Thank you.

**Comment by zalmoxisus** [comment]
Dan's [video](http://youtube.com/watch?v=xsSnOQynTHs) is the best introduction. Here's also [an article I wrote](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83).
