### ISSUE TITLE
DevTools.instrument() is breaking the chrome extension.

### ISSUE THREAD

**Issue by CharlieEarnup** [reduxjs/redux-devtools#406]
Using both `window.devToolsExtension ? window.devToolsExtension() : f => f,` and `DevTools.instrument(),` in the configureStore produces a

```
Uncaught Error: DevTools instrumentation should not be applied more than once. Check your store configuration.
    at instrument.js:664
    at applyMiddleware.js:38
    at <anonymous>:1:27581
    at createStore (createStore.js:64)
    at configureStore (dev.js:23)
    at Object.<anonymous> (index.js:12)
    at __webpack_require__ (bootstrap b2e30df30320e04fef5f:555)
    at fn (bootstrap b2e30df30320e04fef5f:86)
    at Object.<anonymous> (bootstrap b2e30df30320e04fef5f:578)
    at __webpack_require__ (bootstrap b2e30df30320e04fef5f:555)
```

error. 

However doing just `DevTools.instrument(),` breaks the chrome extension.

Is it possible to support both?

**Comment by zalmoxisus** [comment]
What is the use case for supporting both? It would be very tricky to have several lifted stores. The best approach is to check if `window.devToolsExtension` exists, and if not use `DevTools.instrument`.

**Comment by CharlieEarnup** [comment]
I tried that solution and it works, thanks for the help! 😃

**Comment by zalmoxisus** [comment]
@CharlieEarnup you're welcome! Also note that `window.devToolsExtension` was renamed to `window.__REDUX_DEVTOOLS_EXTENSION__`. We'll remove the former in the next major version of the extension.
