### ISSUE TITLE
Upgrade redux-devtools-instrument dependency to v1.9.0

### ISSUE THREAD

**Issue by greena13** [reduxjs/redux-devtools#407]
Currently `redux-devtools` depends on `"redux-devtools-instrument": "^1.0.1"`.

The recently released`redux-devtools-instrument` `v1.9.0` includes an [important fix](https://github.com/zalmoxisus/redux-devtools-instrument/pull/19) to support `redux` `v4.0.0`.

Can we release a new version of `redux-devtools` that has a peer dependency `"redux": "^4.0.0"` and a dependency `"redux-devtools-instrument": "^1.9.0"` (or whatever is most appropriate - I am not sure of the backwards compatibility)?

**Comment by dancrumb** [comment]
Made changes.
Tests pass.
Created PR.
