### ISSUE TITLE
[Question] How do I undo Commit ?

### ISSUE THREAD

**Issue by Industrial** [reduxjs/redux-devtools#408]
Hi.

I only have the Sweep and Commit buttons in the Log window and not the Reset button. This means that when I refresh the page that it keeps the state in the devtools and I can't seem to reset this state.

Can I reset it by executing code in the devtools console manually?

gr,

Tom

**Comment by rmorrise** [comment]
The workaround is to call:
```
store.liftedStore.dispatch({ type: 'RESET' })
```

In my case (using angular-redux), the store is accessible in the AppModule constructor:
```
ngRedux._store.liftedStore.dispatch({ type: 'RESET' })
```

**Comment by shabnam701** [comment]
You probably need to select the **Log Monitor** option  from the first dropdown at top.  You will find **Reset**, **Revert**, **Sweep** and **Commit** options there.

**Comment by zalmoxisus** [comment]
Those buttons are not available in Inspector Monitor, so you'd need Log Monitor for that. For the extension [we'll move the buttons outside](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83).
