### ISSUE TITLE
Example project cannot run successfully

### ISSUE THREAD

**Issue by licaomeng** [reduxjs/redux-devtools#410]
As issue title said, error log as below:

> events.js:183
      throw er; // Unhandled 'error' event
      ^
> Error: listen EADDRNOTAVAIL 30.129.144.64:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! counter-redux@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the counter-redux@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by conorcussell** [comment]
Hey @licaomeng it looks like you have another process running on port 3000. 

Before starting the example application, you can run [`lsof -i tcp:3000`](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac#answer-18706913) in your terminal. This will show you what process is running on that port and you can stop it with [`kill -9 PID`](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac#answer-18706913) the PID will be listed by the previous command. The output looks something like this

<img width="155" alt="screen shot 2018-10-12 at 07 37 32" src="https://user-images.githubusercontent.com/4960622/46852204-18ffd800-cdf2-11e8-8d13-34d6a6876781.png">

**Comment by licaomeng** [comment]
Hi @conorcussell, thank you for your answer, I've resolved this issue, which caused by incorrect host name _**localhost**_ configured in server.js cannot be effective in my environment. After changing to **127.0.0.1**, it works well now.
