### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by zalmoxisus** [reduxjs/redux-devtools#412]
As discussed before, moving all `redux-devtools` related repositories to `reduxjs` organization doesn't look sustainable (though it's still open for discussion). A better way, especially for new contributors, would be to have everything in a monorepo. We could do that in `redux-devtools-extension` as discussed in https://github.com/zalmoxisus/redux-devtools-extension/issues/412 since there's more activity, but using just `redux-devtools` name sounds better and everything started here. So the plan is to keep only this repository, the rest will be archived and the code moved here. I'll add credits for every readme. Maybe we could even add authors of the monitors in the extension, just need an UI for that (something like a monitors store).

The list of repos to be merged (some will be renamed as suggested bellow):
- [x] `redux-devtools` (from current repo)
- [x] [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument)
- [x] [`react-json-tree`](https://github.com/alexkuz/react-json-tree)
- [x] [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector)
- [x]  [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor)
- [x] [`redux-slider-monitor`](https://github.com/calesce/redux-slider-monitor)
- [x] [`redux-devtools-test-generator`](https://github.com/zalmoxisus/redux-devtools-test-generator)
- [x] [`d3tooltip`](https://github.com/romseguy/d3tooltip)
- [x] [`map2tree`](https://github.com/romseguy/map2tree)
- [x] [`devui`](https://github.com/zalmoxisus/devui)
- [x] [`remotedev-utils`](https://github.com/zalmoxisus/remotedev-utils) -> `redux-devtools-core`
- [x] [`remotedev-app`](https://github.com/zalmoxisus/remotedev-app) -> `redux-devtools-core`
- [x] [`remotedev-server`](https://github.com/zalmoxisus/remotedev-server) -> `redux-devtools-cli`
- [x] [`redux-devtools-extension` npm package](https://github.com/zalmoxisus/redux-devtools-extension/tree/master/npm-package)
- [x] [ browser extension](https://github.com/zalmoxisus/redux-devtools-extension)

These repositories could still be maintained outside as either having a maintainer or no changes needed in future (?):
- [x] [`d3-state-visualizer`](https://github.com/reduxjs/d3-state-visualizer/commits/master) (?)
- [x] [`redux-devtools-chart-monitor`](https://github.com/reduxjs/redux-devtools-chart-monitor) (?)
- [`remotedev-serialize`](https://github.com/zalmoxisus/remotedev-serialize) -> `serialize-immutable` (?)
- [`redux-devtools-dock-monitor`](https://github.com/gaearon/redux-devtools-dock-monitor) (?)
- [`redux-devtools-themes`](https://github.com/gaearon/redux-devtools-themes) (?)
- [`redux-devtools-filter-actions`](https://github.com/zalmoxisus/redux-devtools-filter-actions) (?)
- [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) (?)
- [`redux-remotedev`](https://github.com/zalmoxisus/redux-remotedev) (?)
- [`atom-redux-devtools`](https://github.com/zalmoxisus/atom-redux-devtools) (?)

If everybody agrees on, we still have to finish the work in progress in opened PRs, so first will need to:
- [x] fix all issues, except feature requests, for [`2.16`](https://github.com/zalmoxisus/redux-devtools-extension/projects/2),
- [x] finish stack trace functionality started in https://github.com/zalmoxisus/remotedev-app/pull/43 and move to a separate `redux-devtools-trace-monitor` package,
- [x] finish all refactoring, work in progress, implement [new UI](https://github.com/zalmoxisus/redux-devtools-extension/issues/577) and all the updates for `3.0`.

**Comment by zalmoxisus** [comment]
@alexkuz thanks for the reply! I granted permissions for this repository to you. Would you like to continue to maintain [`react-json-tree`](https://github.com/alexkuz/react-json-tree) or better to move it here too? There are no critical issues with it, just few improvements we'd need merged.

**Comment by alexkuz** [comment]
I'd better move it too since I barely support my projects lately

**Comment by zalmoxisus** [comment]
Thanks @alexkuz! When you have some time, please add me as a collaborator to that repo and on npm.

**Comment by alexkuz** [comment]
@zalmoxisus done

**Comment by herodrigues** [comment]
That's a clever idea, because that's a lot of redux-ish applications.
It should be something way more simple just like react-devtools

**Comment by herodrigues** [comment]
That's a clever idea, because there are a lot of "redux-ish" development applications.
It should be something way more simple just like react-devtools.

Browser extension and a standalone Electron app would be enough.
Themes and monitors should be part of the main package.

Also, there are too many projects for simple things and they all have many dependencies and most of them are outdated.
i'm willing to help on this.

**Comment by zalmoxisus** [comment]
@herodrigues definitely, it'll be easier to maintain and contribute. There are use cases where using [monitors separately](https://github.com/reduxjs/redux-devtools/blob/master/docs/Walkthrough.md#usage) is useful (at least till we offer the ability to run the extension directly from client part solving serialization perf issues). Also [`react-native-debugger`](https://github.com/jhen0409/react-native-debugger) and integrations for non-redux are relying on our packages. The monorepo lets us maintain everything like a single package, but still providing the same multiple npm packages.

I did first steps in #416, which seems to work seamlessly. Will move more packages next week.

If you can help with configurations, upgrading dependences, tests, docs..., it'll be much appreciated ☺️

**Comment by zalmoxisus** [comment]
And yes, providing an electron app for `redux-devtools-app` which will silently launch websocket server (without adding `remotedev-server` to the client app) is needed. I was exploring using Chrome Native Messaging instead, but it still requires a [messaging host](https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host), so there are no advantages comparing to current approach of using `socketcluster`/ `remotedev-server` bridge.

**Comment by herodrigues** [comment]
@zalmoxisus how is it going with the browser extension?

**Comment by Methuselah96** [comment]
@alexkuz Do you mind if we also move `react-base16-styling` over here? `react-json-tree` relies on it pretty heavily and it would be convenient to be able to update its dependencies and/or types.

**Comment by Methuselah96** [comment]
@alexkuz Can we move `react-dock` here as well? It has some React 16 deprecation warnings that it would be great to resolve. Thanks!

**Comment by alexkuz** [comment]
@Methuselah96 sure, you should have your access now.

**Comment by Methuselah96** [comment]
Closing since all of the packages mentioned have been moved here. See https://github.com/reduxjs/redux-devtools/issues/530 for future plans.

**Comment by dzienisz** [comment]
how to instal `redux-devtools-extension` `v2.17.1`?
