### ISSUE TITLE
You may not call store.getState() while the reducer is executing.

### ISSUE THREAD

**Issue by alqamabinsadiq** [reduxjs/redux-devtools#413]
I have been working on this application for a couple of months and everything was working fine I was using redux and it's dev tool on chrome. Suddenly today when I tried to run my application on chrome I got this error. I know it's because of the redux dev tool extension I am using. Can you please tell me what should I do to be able to use the extension again.

Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

Devtool version: `2.16.0`
redux: `4.0.1`

**Comment by vietle1** [comment]
same as [issue 588](https://github.com/zalmoxisus/redux-devtools-extension/issues/588)

**Comment by mustkeom** [comment]
I am not able to this.props.functionName(data); in constructor too.

Page is blank withis error:

Uncaught Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

What can I do.

**Comment by alqamabinsadiq** [comment]
Copied from this [url](https://github.com/zalmoxisus/redux-devtools-extension/issues/588#issuecomment-442332672).

In case anyone is looking for temporary work around(for chrome), you can download https://github.com/zalmoxisus/redux-devtools-extension/releases/download/2.15.5/extension.zip and then extract it to some folder.

Type `chrome://extensions` and turn on developer mode from top left and then click on `Load Unpacked` and select the extracted folder for use.

**Comment by irsooti** [comment]
same issue, same versions

Devtool version: 2.16.0
redux: 4.0.1

**Comment by pavolgolias** [comment]
+1 same issue

**Comment by fqf** [comment]
+1 same issue

**Comment by IliaKrainiev** [comment]
same trouble +1

**Comment by stingrayfunk** [comment]
+ 1 same issue

**Comment by fqf** [comment]
it was fixed in 2.16.1 and available on [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)

**Comment by irsooti** [comment]
New fixed version available on Chrome Web Store.

**Comment by dancancro** [comment]
I'm getting this with redux 4.1.2 and redux devtools 4.21.0. Disabling and removing the Chrome extension didn't do anything. Everything works fine on Brave and Opera.
