### ISSUE TITLE
Postcss clashes with redux dev tools.

### ISSUE THREAD

**Issue by Ry10p** [reduxjs/redux-devtools#415]
![nocssmodule](https://user-images.githubusercontent.com/19278457/49198661-0f521580-f349-11e8-9fd4-9109afaf5c76.png)
This is how it is working before I use the CSS Modules in React 16.

![cssmoduleimport](https://user-images.githubusercontent.com/19278457/49198680-2f81d480-f349-11e8-95e2-2180a5604da8.png)
After the use of CSS modules in React 16.

Is this something I am doing wrong or is a possible bug?

Glad to help if I can =).

**Comment by zalmoxisus** [comment]
You could try Inspector monitor, which uses jss, I doubt that would help, but at least would be easier to redefine those classes. That should be solved inside your css, excluding devtools monitor container. Or alternatively you could use browser extension there will be no need to include the component inside you application.
