### ISSUE TITLE
Clearing the action log

### ISSUE THREAD

**Issue by monfera** [reduxjs/redux-devtools#421]
I'm often interested only in the actions pertaining to the specific user interaction (click, drag&drop, menu etc.) and not the entire history since the initial page load. When a user interaction can lead to multiple actions, it's super hard to know what the new actions are. So I'd like to be able to erase the action log, eg. with Ctrl-K, similar to how the dev console can be erased.

Having said that, I'm surprised it's not avaliable aready, given the level of convenience it'd bring, so maybe I'm doing something wrong. Admittedly I believe it's best if a user action leads to a single action for the store, which is almost like an unspoken redux principle, and I even agree with it, but sometimes one has to work with preexisting code, to be refactored later.

**Comment by zalmoxisus** [comment]
The difference with logs from dev console is that here we should also be able to recompute actions to get the exact state, and by excluding/erasing certain actions there could be an inconsistency. What we provide as an alternative is to just hide them (while they are still stored in the history). For browser extension add `actionsBlacklist` / `actionsWhitelist` or `predicate` option (see [the API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist)). If you're including it as a component, then the same can be achieved with [`redux-devtools-filter-actions`](https://github.com/zalmoxisus/redux-devtools-filter-actions) or [`redux-devtools-filterable-log-monitor`](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/).

**Comment by monfera** [comment]
Thanks for the answer! Btw. I wasn't looking for excluding past actions in any sense other than just not viewing past actions that no longer matter to me, not sure where I gave that impression (maybe "erase the action log" should've been "hide/remove from the view the rendered rowa of the action log"). 

I don't understand the part about inconsistency, or what functionality would be jeopardized by _not_ showing old actions. (Or even, by not storing old actions - if I'm not interested in the history then there won't be functions requiring these past actions, unlike when filtering certain action types, maybe I'm overlooking something.) Even if there's functionality tied to keeping around old actions (or specifically, all the states associated with these old actions, going beyond Redux itself, eg. undoing actions which afaik Redux Dev Tools doesn't support afaik) my suggestion was about simply not showing actions prior to a specific action, which feels like a _view_ question.

The way Redux works is conducive to modeling it as a starting state and a subsequent series of actions that make new states, and what the starting state is, is arbitrary. Especially when it comes to debugging - coders can decide that they're simply not interested in _viewing_ anything prior to whatever action. Even the name "Redux" may have come from it, it's basically a reducer. 

The otherwise useful functionality of hiding specific _action types_ is orthogonal to the original suggestion, although seems analogous. If that's useful, possible and allowed, then eliding historical actions could be as well.

Btw. please don't interpret any of this other than a feature suggestion simply based on what I'd find useful and analogous with similar Ctrl-K things in Dev Console and console logs, these are well used features for the same reason: allowing the developer to focus on what matters.
