### ISSUE TITLE
Can you publish react-json-tree to npm with packed code?

### ISSUE THREAD

**Issue by panlina** [reduxjs/redux-devtools#442]
I'm using `react-json-tree` on npm. Currently(`v0.11.1`) it contains only the source code and transpiled code, but they are still CMD modules.

It will be convenient to use if a packed-in-one script is provided, just like most libraries. Can you publish like that?

**Comment by zalmoxisus** [comment]
@panlina sure. Would you like to submit a PR adding webpack for building an umd package? Can take [`map2tree`](https://github.com/reduxjs/redux-devtools/blob/master/packages/map2tree/package.json#L9) as an example just it's using an old version of webpack, would be preferably to use the a latest.

**Comment by zalmoxisus** [comment]
It's available in `react-json-tree@0.11.2` in `umd` folder as `react-json-tree.js` and `react-json-tree.min.js`. Note that react and react-dom should be included separately.

**Comment by panlina** [comment]
Oh, thanks a lot. I missed your reply. I would have been glad to submit a PR. 😄
