### ISSUE TITLE
Error in response to storage.get: TypeError: Cannot read property 'filter' of undefined.

### ISSUE THREAD

**Issue by Cyrus-d** [reduxjs/redux-devtools#450]
Getting this error from last night, at first I thought its to do with my app, but when I tested with a random redux boilerplate I get the same error. the error will disappear when disabling the extension.

Error: 
Error in response to storage.get: TypeError: Cannot read property 'filter' of undefined
Unchecked runtime.lastError while running storage.get: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4)

chrome version: 71.0.3578.98 (Official Build) (64-bit) 
windows 10 64-bit
extension version: 2.17.0

Is it just me or anyone else getting this error?

**Comment by youhaowei** [comment]
I got the same.

**Comment by DanuVIP** [comment]
I got the same, doenst make sense why tho.

**Comment by DanuVIP** [comment]
## GUYS, after finally figuring it out- I found the solution!
I don't have any idea of how it happened, but when you encountered this error, you likely managed to delete the entire Chrome extension folder.  **Congratulations.**

### It aint that bad, you can still fix it: <sup>(kindof)</sup>

1. Go to the following folder and remove your buggy extension.
   >[chrome://extensions/](chrome://extensions/)
2. Now go to your Chrome-Extensions Folder (the one you are working on) and rename it.
3. Then add it back to chrome.
   > [chrome://extensions/](chrome://extensions/)
   
### Why does this work?
> Chrome saves your data at `C:\Users\[login_name]\AppData\Local\Google\Chrome\User Data\Default\Extensions` <sup>(by default)</sup>. If you managed to delete the whole folder of your extension, Chrome doesnt know where to put the files. This results in "_`MANIFEST-000001: Unable to create sequential file`_" . You cant just create a new folder with the same ID and a version_folder inside of it, as the essential data is still missing. Since you also cannot change the ID of your Chrome extension, you are left with no choice but to create a new extension.

**Comment by DanuVIP** [comment]
_actually- at this point im not even sure if the cause is that you deleted the extensions folder. 
I've run into the same error twice again and really have no idea how it happened. All I do is basic read and write with the chrome storage api, no fancy stuff involved. If someone finds out why and possibly know a better solution.. please tell us!_
