### ISSUE TITLE
redux-devtools-cli documentation doesn't match published module

### ISSUE THREAD

**Issue by madcapnmckay** [reduxjs/redux-devtools#453]
Hi @zalmoxisus I was redirected from `remotedev-server` to the new `redux-devtools-cli` which looks great btw. But when I installed it and tried to use the `--open` it didn't work.

I then realized that the version that had been installed is `0.0.1-1` not `1.0.0-1` as is in master.

If that was intended and this package is a wip then you might want to make a note on the readme.

**Comment by jnbt** [comment]
@zalmoxisus I also think the published version (0.0.1-1) is a little bit broken. Starting the server works, but it just responds with a 404 status code with `Cannot GET /`. I tried to find the published version of `worker.js` in this GitHub repo, but I failed. When looking at the current state in `master` it seems already fixed.

**Comment by Methuselah96** [comment]
Resolved with [`redux-devtools-cli@1.0.0-2`](https://github.com/reduxjs/redux-devtools/releases/tag/redux-devtools-cli%401.0.0-2).
