### ISSUE TITLE
Link to setup walkthrough 404's

### ISSUE THREAD

**Issue by donpinkus** [reduxjs/redux-devtools#455]
On the main readme for [redux-devtools](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools), the walkthrough link 404s:

https://github.com/reduxjs/redux-devtools/blob/master/packages/redux-devtools/docs/Walkthrough.md

**Comment by zalmoxisus** [comment]
The docs we moved to monorepo's root folder, should be https://github.com/reduxjs/redux-devtools/blob/master/docs/Walkthrough.md. Thanks for reporting it. If you can submit a PR that would be welcome or I will fix it later.

**Comment by donpinkus** [comment]
@zalmoxisus I'll take care of it, you're busy enough :P

**Comment by Methuselah96** [comment]
Resolved by https://github.com/reduxjs/redux-devtools/pull/477.
