### ISSUE TITLE
Diff monitor with React 16?

### ISSUE THREAD

**Issue by donpinkus** [reduxjs/redux-devtools#457]
When using the redux-devtools extension, it has a feature that lets you see the diff in your state.

It seems log-monitor does not come with this, and diff-monitor doesn't work for React 16.

Has anyone created a monitor for diff'ing redux with React 16 in redux-devtools? If not I can attempt it.

**Comment by zalmoxisus** [comment]
Looks like diff-monitor wasn't updated for several years. You can use [`redux-devtools-inspector`](https://github.com/reduxjs/redux-devtools/tree/master/packages/redux-devtools-inspector). It has Diff tab, same as in the extension.

**Comment by donpinkus** [comment]
Thanks @zalmoxisus! Closing.
