### ISSUE TITLE
react-json-tree: customize JSONArrow

### ISSUE THREAD

**Issue by QuentinBrosse** [reduxjs/redux-devtools#464]
Hi !

According to https://github.com/alexkuz/react-json-tree/issues/100, it is not possible to customize the [`JSONArrow` component](https://github.com/reduxjs/redux-devtools/blob/master/packages/react-json-tree/src/JSONArrow.js).

I need to change this arrow by a `+/-` or another icon. Does PR are welcome or you don't want to offer this option ?

Thanks a lot ! :)

**Comment by dwcIntegral** [comment]
Would love this option as well. Being able to simply replace the `JSONArrow` with my own `customArrow` component would be ideal. Thanks for a great tool!
