### ISSUE TITLE
Redux-devtools is still crashing with Redux 4 on Electron

### ISSUE THREAD

**Issue by dawnmist** [reduxjs/redux-devtools#465]
Related issues:
* https://github.com/reduxjs/redux-devtools/issues/391
* https://github.com/zalmoxisus/redux-devtools-extension/issues/632

I've been testing updating an electron app from redux 3 to redux 4, but running the app in Electron with redux 4 causes the app to fail in createStore with the error: "`Error: cannot read property 'state' of undefined`".

Running the exact same code but compiled for `web` and viewing it in a normal browser works as expected with no error. Viewing the same site in Electron fails.

I've tried both the `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` method of inclusion as well as the standard `redux-devtools-extension` `composeWithDevTools` method of inclusion. Both methods work for Google Chrome, both methods throw the above error during `createStore` when viewed in Electron's browser.

```
TypeError: Cannot read property 'state' of undefined
    at unliftState (<anonymous>:2:31678)
    at Object.getState (<anonymous>:2:31745)
    at connectRoutes.js:492
    at <anonymous>:2:1425
    at createStore (redux.js:79)
    at _callee2$ (configureStore.ts:107)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.(:3000/anonymous function) [as next] (https://localhost:3000/static/js/0.chunk.js:63821:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

I've also tried pointing Electron at the `web` compiled version as well as the `electron-renderer` compiled version, which shows the same error. So it appears to be specific to running in Electron itself rather than whether it was compiled for `web` or `electron-renderer`.

Using the `forceDownload` parameter and adding a console.log to `electron-devtools-installer` to echo out the contents of the manifest for what it is downloading confirms that `electron-devtools-installer` is downloading version 2.17.0 of `redux-devtools`. So this error is occurring in the current release.

**Comment by dawnmist** [comment]
And now after 2 hours of testing/fiddling, it has suddenly started working properly in Electron. I suspect that the forceDownload caused it to grab the newer version of redux-devtools, but that newer version wasn't used until the _next_ load of the app. So it appeared that forcing the download of the current version didn't work - but in reality it just hadn't used it yet.

**Comment by framerate** [comment]
@dawnmist I'm having this exact issue I believe on my linux dev laptop running Solus HOWEVER

My VM running Solus on my desktop works fine
My Chrome OS laptop running debian works fine.

Any further pointers for me?

**Comment by framerate** [comment]
@dawnmist Nevermind! I misread something, forceDownload was the culprit, had to let it finish (with errors in my app trying to load something mid-download) and restart and it worked!
