### ISSUE TITLE
shouldExpandNode does not re-rendering nodes on observable value change

### ISSUE THREAD

**Issue by SourceCipher** [reduxjs/redux-devtools#469]
When I pass via props the observable value to the component `shouldExpandNode={() => this.props.expand}` at first it renders all okay, but changing observable value `this.props.expand` will not make any nodes expand or collapse. I debugged and the component receives correct props and the render is being triggered. 

**SOLUTION:**
I found the solution after I posted this. I used to render the component like this (didnt worked):

```
 render() {
    return (
      <JSONTree data={this.props.dataSource} theme={theme} shouldExpandNode={() =>  this.props.expand} />
    );
  }
```

after doing this (worked):

```
 render() {
    let expand = this.props.expand;

    return (
      <JSONTree data={this.props.dataSource} theme={theme} shouldExpandNode={() => expand} />
    );
  }
```

**Comment by Methuselah96** [comment]
@SourceCipher Can you create a reproduction of this bug? Here's an example of it working the way I would expect: Can one of you create a reproduction of the bug so that I can look into this? Here's an example of it working the way that I would expect: https://codesandbox.io/s/keen-goldstine-c5rd3?file=/src/index.js.

**Comment by Methuselah96** [comment]
Never mind, I was able to reproduce it (https://codesandbox.io/s/optimistic-snow-0srg6?file=/src/index.js). I'll look into it when I get a chance.

**Comment by Methuselah96** [comment]
I don't think this is an issue with `react-json-tree`, it's just an issue with React in general. I don't know exactly what the rest of your code looks like, but the problem in my reproducible case was a side effect of state or props change to a parent component not being propagated to the child component (see https://medium.com/@admin_86118/react-re-render-child-components-on-parent-state-change-387720c3cff8). Feel free to follow up if that doesn't resolve your issue.
