### ISSUE TITLE
Google Maps Map object crashes extension

### ISSUE THREAD

**Issue by Digicrest** [reduxjs/redux-devtools#475]
I'm literally the worst so I could just be misunderstanding how to use react/redux properly (only been using it a few weeks) but when I try to save a google maps map object the extension crashes.

It works fine with redux logger.

```js
const map = new window.google.maps.Map(document.getElementById('map'), {
      center: { lat: this.props.mapCentre.lat, lng: this.props.mapCentre.lng },
      zoom: 17
});
this.props.saveMap(map)
```

**Comment by timdorr** [comment]
You shouldn't put complex objects into the store: https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state
