### ISSUE TITLE
React 16.9: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by bluepeter** [reduxjs/redux-devtools#480]
See https://fb.me/react-async-component-lifecycle-hooks and https://reactjs.org/blog/2019/08/08/react-v16.9.0.html for details. At minimum, this needs the prefix `UNSAFE_` adding to these calls.

![json](https://user-images.githubusercontent.com/2158187/63060496-4badad80-bea7-11e9-979a-3d325d0a2c86.png)

**Comment by Type1J** [comment]
This issue affects a good number of our projects. As the error says, it's for the upcoming async rendering.

I'm not sure if this use will cause any issues with async rendering, and we should at least try `UNSAFE_` once React 17 is released, which would require no further modification.

If it does cause issues in React 17, then we'll cross that bridge when we come to it.

Here's the output of ` grep -r componentWillReceiveProps *` in this project (with no node_modules!).

```
packages/devui/src/ContextMenu/ContextMenu.js:  componentWillReceiveProps(nextProps) {
packages/devui/src/Editor/Editor.js:  componentWillReceiveProps(nextProps) {
packages/devui/src/Tabs/Tabs.js:  componentWillReceiveProps(nextProps) {
packages/devui/src/Tabs/TabsHeader.js:  componentWillReceiveProps(nextProps) {
packages/react-json-tree/src/index.js:  componentWillReceiveProps(nextProps) {
packages/react-json-tree/src/JSONNestedNode.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-core/src/app/components/Settings/Connection.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-core/src/app/containers/monitors/Dispatcher.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-core/src/app/containers/monitors/InspectorWrapper/ChartTab.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-core/src/app/containers/monitors/InspectorWrapper/SubTabs.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-inspector/src/ActionList.jsx:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-inspector/src/DevtoolsInspector.js:  componentWillReceiveProps(nextProps) {
packages/redux-devtools-log-monitor/src/LogMonitor.js:  componentWillReceiveProps(nextProps) {
```

Is there anyone around to make these changes?

If we made a PR, would it be reviewed?

**Comment by bluepeter** [comment]
@Type1J it doesn't look as though this repo is maintained, so I'd reco forking and fixing there... and pointing the rest of us to your fork :)

**Comment by Type1J** [comment]
I'd hope that there would be at least 1 maintainer (someone that can merge PRs) to respond. I'll give it a few days.

**Comment by neolefty** [comment]
Any responses? I'd like to get a version of the JSON tree viewer at least that only uses the current React API. Maybe it's time to add a new maintainer or fork after all ...

**Comment by bluepeter** [comment]
Looks like we are going to have to fork.

This is a recurrent problem w/ open source. I don't get why maintainers can't even *respond* or delegate the repo to someone else?!

**Comment by bluepeter** [comment]
@timdorr can you help please??

**Comment by timdorr** [comment]
See #502. I've _just_ gotten the keys to the castle, so it will take me a bit to get a handle on things and help out here.

**Comment by bluepeter** [comment]
Super! Glad to have your steady hands @timdorr at the tiller!

**Comment by Type1J** [comment]
@timdorr Personally, I'm just glad that somebody is able to help out! Your work and time are appreciated.

**Comment by bluepeter** [comment]
@timdorr this seems to still be an issue... is there a new version that's coming hopefully?
