### ISSUE TITLE
Please publish the latest redux-devtools-inspector

### ISSUE THREAD

**Issue by kondi** [reduxjs/redux-devtools#481]
In npmjs the latest version is v0.11.3, two years old https://www.npmjs.com/package/redux-devtools-inspector. That version does not have the `hideMainButtons` prop for the component (https://unpkg.com/redux-devtools-inspector@0.11.3/lib/DevtoolsInspector.js), however in the version in github master it is there: https://github.com/reduxjs/redux-devtools/blob/master/packages/redux-devtools-inspector/src/DevtoolsInspector.js#L216.
Also, the version in this repo is marked as v0.11.0, but quite different from the one published into npm as v0.11.0.

It is really not clear how can I access this version from npm and where the source is actually came from (to this repo). Maybe bump the version and optionally create an npm org and publish it.

I haven't checked the other subprojects (packages), but I can imagine this is not only case for the `redux-devtools-inspector`.

Probably related to https://github.com/reduxjs/redux-devtools/issues/412

**Comment by Methuselah96** [comment]
Published: https://github.com/reduxjs/redux-devtools/releases/tag/redux-devtools-inspector%400.12.0
