### ISSUE TITLE
Large Array Ellpisized in react-json-tree

### ISSUE THREAD

**Issue by taylorharwin** [reduxjs/redux-devtools#498]
When passing a data object containing an array of 80 elements, the elements 46-75 are ellipsized. This prevents someone from using CTRL+F to find a value within that collapsed set.

Is there a way to control or override this behavior? 

<img width="169" alt="Screen Shot 2020-01-31 at 5 16 13 PM" src="https://user-images.githubusercontent.com/5825244/73584506-c9fa0e00-444d-11ea-9304-8f6ee0f393ec.png">

**Comment by simsonek** [comment]
I have checked that you can set custom value for the arrays size which is ellipsized

`<JSONTree data={data} collectionLimit={10000} /> `
or higher value if needed should work

**Comment by Methuselah96** [comment]
@taylorharwin Does that sufficiently address your issue?
