### ISSUE TITLE
Add to the Microsoft Edge extension store

### ISSUE THREAD

**Issue by deasems** [reduxjs/redux-devtools#500]
Please add this extension to the MS extension store so that it can be used in the chromium-based version of Edge - https://microsoftedge.microsoft.com/addons/category/Edge-Extensions

I believe docs for publishing to this store are here - https://developer.microsoft.com/en-us/microsoft-edge/extensions/

**Comment by arvind0598** [comment]
Has there been any update for this?

**Comment by Methuselah96** [comment]
No update. Our focus so far has been trying to get a new release of some of the packages published, but it doesn't look like that's happening as quickly as I had hoped. I will be gone for the next two weeks, but after that I will see if I can get the old/last published version of the DevTools added to the MS extension store.

**Comment by arvind0598** [comment]
I did manage to find this and it does install, but I haven't really tested out any functionalities yet. Any idea how its on the store right now?

https://microsoftedge.microsoft.com/addons/detail/react-developer-tools/gpphkfbcpidddadnkolkpfckpihlkkil

**Comment by Methuselah96** [comment]
That's React Developer Tools not Redux Developer Tools.

**Comment by arvind0598** [comment]
Whoops. My bad.

**Comment by Methuselah96** [comment]
I've submitted the extension to the Microsoft Edge extension store and am waiting for it to be reviewed by Microsoft.

**Comment by Methuselah96** [comment]
The extensions has been published to the Edge Add-ons store: https://microsoftedge.microsoft.com/addons/detail/nnkgneoiohoecpdiaponcejilbhhikei.
