### ISSUE TITLE
NPM version mismatch

### ISSUE THREAD

**Issue by earksiinni** [reduxjs/redux-devtools#501]
`package.json` for this package claims that the version is `1.0.0`, whereas NPM claims that the latest available version is `0.0.1-1`: https://www.npmjs.com/package/redux-devtools-cli

Could we get an updated version in NPM?

**Comment by Methuselah96** [comment]
We're working on getting this project back to a maintained state (see https://github.com/reduxjs/redux-devtools/issues/502). Once that happens we'll be sure to make sure to publish the latest version of all the packages.

**Comment by Methuselah96** [comment]
Duplicate of https://github.com/reduxjs/redux-devtools/issues/453.
