### ISSUE TITLE
Redux devtools with "autoselect instance" -> will autoselect @react-navigation

### ISSUE THREAD

**Issue by aymkin** [reduxjs/redux-devtools#504]
I use React Native Debugger to inspect the redux state of my react native app.

React navigation automatically creates an instance called "@react-navigation" in the redux devtools each time I live reload (see screenshot).

With auto select instances turned on, @react-navigation takes precedence over the new redux store instance. It's very annoying because I must manually select the new redux store instance each time I live reload.

- every load @react-navigation appears in the autoselected instances
- every time redux store has a different name

![screenshot](https://user-images.githubusercontent.com/10321850/76186361-c55a0f80-61da-11ea-8091-999f395af562.png)

React Native Debugger app version: [0.10.6]
React Native version: [0.61.4]
Platform: [iOS]
Is a real device: [No]
Operating System: [FILL THIS OUT: macOS]

**Comment by samipshah100** [comment]
Same issue

**Comment by orszaczky** [comment]
is there a way to turn off this autoselect feature? it's super annoying, every time it auto selects some totally irrelevant state instead of the currently open page. not even sure where this whole list of other states come from...
