### ISSUE TITLE
Remove instance

### ISSUE THREAD

**Issue by unlocomqx** [reduxjs/redux-devtools#525]
I'm using redux devtools to monitor svelte components state and each component has a devtools instance. I need to remove the instance once the component gets destroyed. Does the API allow removing an instance?
I used `devTools.unsubscribe()` but that doesn't remove the instance
Thank you

**Comment by Methuselah96** [comment]
@unlocomqx It seems like this is a duplicate of https://github.com/reduxjs/redux-devtools/issues/366. Can you verify that it is?

**Comment by unlocomqx** [comment]
It's the same issue
I'll close this one then
