### ISSUE TITLE
react-dock: Resize: handle touch devices with touch events.

### ISSUE THREAD

**Issue by kuosman** [reduxjs/redux-devtools#595]
Hi, Can you add this feature: https://github.com/alexkuz/react-dock/pull/27

**Comment by Methuselah96** [comment]
Yeah, if @ArthurMaroulier is still around he can create a PR or you can go ahead and do it yourself since it doesn't look like he's active anymore.

**Comment by kuosman** [comment]
Hi, ok. I created PR: https://github.com/reduxjs/redux-devtools/pull/596
