### ISSUE TITLE
react-dock: componentWillReceiveProps with react 16.9.0

### ISSUE THREAD

**Issue by ukch** [reduxjs/redux-devtools#630]
Ref: alexkuz/react-dock#40

For quite some time, React has been throwing up a warning about this component using the deprecated `componentWillReceiveProps` interface. The simplest solution here is to do a find-replace and use `UNSAFE_componentWillReceiveProps` instead. Alternatively, you could refactor the component to use `getDerivedStateFromProps` instead.

Here's the full warning from React:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>
> Please update the following components: Dock

**Comment by Methuselah96** [comment]
I resolved this in [the PR that added this package](https://github.com/reduxjs/redux-devtools/pull/590). This issue should be resolved in `react-dock@0.3.0`, which I released just now. Let me know if that doesn't resolve your issue.

**Comment by ukch** [comment]
Thanks @Methuselah96 . I can confirm the issue appears to be fixed in the new version.
