### ISSUE TITLE
Permissions requiring all_urls

### ISSUE THREAD

**Issue by raybooysen** [reduxjs/redux-devtools#663]
Hi all

We are trying to onboard redux-devtools into our large organisation and our security team has flagged this extension as requesting [all_urls](https://github.com/reduxjs/redux-devtools/blob/master/extension/src/browser/extension/manifest.json#L68) as a security risk.

I compared this to the [react dev tools](https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/chrome/manifest.json#L43) which require only:
```
  "permissions": ["file:///*", "http://*/*", "https://*/*"],

```

Is this something you'd accept a PR to change to this smaller sub-set?

**Comment by raybooysen** [comment]
I've clarified with our security folks and their concern is around the possibility of ftp as an allowable URL (incorrect or not, this is the blocker I face to use this dev tool internally).

**Comment by Methuselah96** [comment]
@raybooysen Yeah, PRs are welcome for that change.

**Comment by raybooysen** [comment]
Thanks @Methuselah96 .  Would it be possible to do a release with this change so we can integrate this into our org?
