### ISSUE TITLE
Wrong order of dispatched actions?

### ISSUE THREAD

**Issue by sicLotus** [reduxjs/redux-devtools#665]
Hi! I'm still pretty new to the Redux world and have encountered the following problem:

My actions are logged in the DevTools in the wrong order (at least in my understanding).

I dispatch an action "A" from the UI. This action is handled by a custom middleware. There I dispatch a second action "B", which is then handled by the reducer.

The DevTools logs first the action B and then the action A. But I dispatched the actions in different order? I expected the action A to be logged first.

Did I miss something here or is this a bug?

**Comment by Methuselah96** [comment]
Is the custom middleware asynchronous for action "A"?

**Comment by Akxe** [comment]
If action A triggered action B then B finished before A, since A had to wait for B to finish, to be able to finish its callback...

**Comment by Methuselah96** [comment]
Closing pending response from author.
