### ISSUE TITLE
Why is the JSONTree data property a required property?

### ISSUE THREAD

**Issue by chriswoodley** [reduxjs/redux-devtools#684]
I am using the `JSONTree` component in my project and I noticed when the `data` property is `undefined` it displays `undefined` in the output and at the same time I get the following console warning:

```
Warning: Failed prop type: The prop `data` is marked as required in `JSONTree`, but its value is `undefined`.
        in JSONTree (created by JSONDisplay)
        in JSONDisplay (created by TemplateSelectionForm)
        in div (created by styled.div)
        in styled.div (created by TemplateSelectionForm)
        in div (created by FormGroup)
        in FormGroup (created by FormGroup)
        in FormGroup (created by TemplateSelectionForm)
        in div (created by Form)
        in form (created by Form)
        in Form (created by TemplateSelectionForm)
        in TemplateSelectionForm
        in Router (created by BrowserRouter)
        in BrowserRouter
        in ThemeProvider
        in Provider
```

This does not break the application and it properly displays `undefined`, However it causes unit tests to fail whenever this warning occurs. What is the intended behavior when the `data` prop is undefined? Seems confusing to have that prop required but yet it appears to display correctly in the output.

**Comment by Methuselah96** [comment]
Interesting, I would have expected if you explicitly passed `undefined` in as a prop that it wouldn't give the prop type warning. Can you make a PR to remove the `.isReuquired` from [the `data` prop type](https://github.com/reduxjs/redux-devtools/blob/master/packages/react-json-tree/src/index.tsx#L107)? Thanks!

**Comment by chriswoodley** [comment]
PR has been created. See https://github.com/reduxjs/redux-devtools/pull/685/files
