### ISSUE TITLE
More inclusive API

### ISSUE THREAD

**Issue by zsajjad** [reduxjs/redux-devtools#686]
First of all; Thanks a lot to all the contributors for maintaining such an amazing tool. You're definitely making our lives much much easier.

While working on our recent blog post about Redux DevTool, I realized that parameters like actionWhitelist & actionBlacklist are not inclusive. Can we move it to allowList & blockList just to be more inclusive?

I think this will be a good contribution to the growth of society. I am ready to submit a PR for this if maintainers agree on this.

@Methuselah96

**Comment by Akxe** [comment]
Why? Does this bring peace to someone? This is possibly breaking with little to no benefit.

**Comment by BartusZak** [comment]
In my opinion an overkill.
