### ISSUE TITLE
Incorrect peer dependency with React 17.0.1

### ISSUE THREAD

**Issue by medihack** [reduxjs/redux-devtools#698]
I added `redux-devtools` with `yarn add --dev redux-devtools` and get this warning now:

    redux-devtools@3.7.0" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".

I know, most likely I can just ignore it. But if it really supports React 17 (in my case v17.0.1) it would be nice to just go away ;-)

**Comment by markwoon** [comment]
+1

Would also like to see `react-json-tree`'s peer dependency updated as well.

**Comment by veeramarni** [comment]
Any update on it?
