### ISSUE TITLE
UI is extremely buggy

### ISSUE THREAD

**Issue by rendomnet** [reduxjs/redux-devtools#699]
i'm using latest version and UI is super bad.
`redux-devtools --open`

1. the themes selector is transparent and cant be clicked
![image](https://user-images.githubusercontent.com/18900210/106263171-3b7dbf80-624e-11eb-8b0b-06feca704e03.png)

2. I cant see latest action because it is out of scroller area.
![image](https://user-images.githubusercontent.com/18900210/106269469-bcd95000-6256-11eb-99b5-afa438912c27.png)

3. And most annoying  when I click action button to see the action data. info area is not updated and I have to click "raw" tab and then back "tree" tab to update info area.

**Comment by Methuselah96** [comment]
Thank you for the issue! The `redux-devtools-cli` package is not stable yet (its version is `1.0.0-4`). If you would like a stable package, try using [`remotedev-server`](https://github.com/zalmoxisus/remotedev-server) until this package stabilizes.

**Comment by rendomnet** [comment]
@Methuselah96 but why closing this issue?
Maybe close it when issue will be resolved?

Other people will know that current version have problem.

**Comment by Methuselah96** [comment]
@rendomnet Can you give me more details about what system you're on (OS and browser)? I'm not seeing the same issues with the UI as you are in your top screenshot.

**Comment by rendomnet** [comment]
@Methuselah96 it was under Mac. I used it for electron debugging.

**Comment by Methuselah96** [comment]
Resolved by https://github.com/reduxjs/redux-devtools/pull/709 and https://github.com/reduxjs/redux-devtools/pull/728.

@rendomnet Let me know if you run into any more bugs in the UI.
