### ISSUE TITLE
 @redux-devtools/cli is broken, Cannot find module '../dist/bin/redux-devtools.js'

### ISSUE THREAD

**Issue by yqrashawn** [reduxjs/redux-devtools#705]
there's no `bin` folder in `dist`
```sh
❯ ls ~/.config/yarn/global/node_modules/@redux-devtools/cli/dist
index.js
```
![image](https://user-images.githubusercontent.com/15090582/110271556-483ac380-8003-11eb-9055-579eef146610.png)

**Comment by apperside** [comment]
The same here, 824 packages where installed, but not what's really needed 😅
<img width="985" alt="Screenshot 2021-03-31 at 20 10 23" src="https://user-images.githubusercontent.com/5955338/113191042-5f18b280-925d-11eb-90fa-b04907abcf09.png">
