### ISSUE TITLE
Link to old repo

### ISSUE THREAD

**Issue by dzienisz** [reduxjs/redux-devtools#710]
Hi why we link in this repo to this old repo

https://github.com/zalmoxisus/redux-devtools-extension#installation?

why this instructions aren't moved to this repo?

**Comment by Methuselah96** [comment]
The instructions have been moved to this repo: https://github.com/reduxjs/redux-devtools/tree/master/extension#installation.

Is there a specific link that needs to be updated? This repo is still in a state of transition, but I'll hopefully have more time in the coming months to finish the transition.

**Comment by timdorr** [comment]
I've updated the URL for the next published version.
