### ISSUE TITLE
Chrome web store link is broken

### ISSUE THREAD

**Issue by MarkoCen** [reduxjs/redux-devtools#713]
[Chrome](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)

![image](https://user-images.githubusercontent.com/8303274/117044609-a1aa3080-acdc-11eb-8650-b9b6141320cd.png)

**Comment by markerikson** [comment]
Yes, Google decided to take down the Redux DevTools Extension:

https://twitter.com/timdorr/status/1389553537659588608

We've submitted a request to have that reviewed and hopefully resolved, but no ETA:

https://twitter.com/timdorr/status/1389587796810244117

**Comment by Methuselah96** [comment]
By the way, we might be able to back-port this PR if necessary to tighten the `<all_urls>`.

**Comment by iamdipankarj** [comment]
Yup, cannot access the extension on webstore.

**Comment by TehJudas** [comment]
Can't seem to install via  chrome://extensions with the .zip folder either, says it's missing the manifest file

**Comment by Methuselah96** [comment]
If you want to install via the zip folder, try 2.17.0. The zip folder for 2.17.1 is for Firefox. Alternatively you can just replace the manifest file with the correct one which can be found [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/manifest.json). That's the only difference between the Firefox and Chrome builds.

**Comment by TehJudas** [comment]
Working with the 2.17.0, thank you!

**Comment by timdorr** [comment]
Google gave us an exemption and we're back on the store. https://twitter.com/timdorr/status/1389995877989851143

I'm looking to resolve the issue (extraneous `tabs` permission) and will publish a 2.17.1 soon to make sure we don't get taken down again.
