### ISSUE TITLE
Getting peer dependency warnings when installing the latest version of @redux-devtools/cli

### ISSUE THREAD

**Issue by kaiyoma** [reduxjs/redux-devtools#727]
There are new peer dependency warnings during the linking phase of `yarn install`:

```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@redux-devtools/cli > @redux-devtools/app > @redux-devtools/inspector-monitor-test-tab@0.7.0" has incorrect peer dependency "@redux-devtools/inspector-monitor@^0.14.0".
warning "@redux-devtools/cli > @redux-devtools/app > @redux-devtools/inspector-monitor-trace-tab@0.2.0" has incorrect peer dependency "@redux-devtools/inspector-monitor@^0.14.0".
```

This is happening with @redux-devtools/cli 1.0.0-7.

**Comment by Methuselah96** [comment]
Yeah, that's an unfortunate consequence of Lerna not bumping peer dependency versions and still being in the 0.x.y range of releases. I'll have to think about how best to address this. Probably bumping the inspector to 1.x.y makes the most sense.
