### ISSUE TITLE
Idea: Interface modularity

### ISSUE THREAD

**Issue by dannykingme** [reduxjs/redux-devtools#74]
A problem I've noticed in the UI is that everything feels very ad hoc, and components don't really consider each other. The changes in #48 helped organize what's already built, but didn't do much to anticipate new features.

After chatting with @gaearon I learned that there's still a lot of cool stuff yet to be added, e.g., state scrubbing, save & load, granular commit/sweep actions, etc. So in an effort to prevent some painful redesigns in the future, I tried thinking of a few simple ideas that'll help organize what's in the devtools UI now, and what might come later.

<a href="https://danny.precursorapp.com/document/17592201472774"><img src="https://danny.precursorapp.com/document/17592201472774.svg"></a>

<a href="https://danny.precursorapp.com/document/17592201472774">Doc</a> • <a href="https://danny.precursorapp.com/document/17592201472774.svg">SVG</a> • <a href="https://danny.precursorapp.com/document/17592201472774.svg?as-of=13194154961931">Original</a>

A few questions I assumed would be asked:
#### Why not keep top-level events expanded?

The current implementation makes it hard to manipulate a lot of items at once, since just a few of them fill up the view. This isn't a huge problem at the moment, but if concepts like granular control of global actions, state scrubbing, or filtering are introduced the problem will grow.
#### Why action drawers?

Since everything is ad hoc at the moment, the UI keeps running out of room. The same effect could be achieved with a drop down or similar, but a drawer for event actions create consistency between the global actions. And since many of the actions would actually be the same (e.g., delete, commit, etc.) you can just use the same component and change the content based on context.
#### Why icons for actions?

Besides making it easier to quickly identify actions, it'll also act as a uniform guide that's easier to design around. I.e., components containing large amounts of actions are easy since they all have the same dimensions, etc.

I'll be iterating on this wireframe and adding new ones. I'm hoping to have time to implement some of them myself soon as well. But at the very least, these wireframes can serve as a reference. Very open to feedback on anything.

**Comment by dannykingme** [comment]
Made the <a href="https://danny.precursorapp.com/document/17592201472774">Precursor doc public</a>. Feel free to iterate, make notes, etc.

**Comment by gaearon** [comment]
Thank you for looking into this! I think the most interesting part is how to fit the workflow (get to the state you like, choose the actions to work on, iterate on them in replay mode, come back to normal mode) in terms of this architecture.

I'll be busy with another project for some time, but please feel free to share more ideas!
