### ISSUE TITLE
After Chrome update DevTools not visible anymore

### ISSUE THREAD

**Issue by nicewaytodoit** [reduxjs/redux-devtools#752]
I have updated to :
Google Chrome is up to date
Version 91.0.4472.114 (Official Build) (64-bit)

Now Redux - dev tools are not visible anymore, same goes for React Developer Tools :/

Redux-Dev tools Version 2.17.2

**Comment by Methuselah96** [comment]
Interesting. I'm on that version of Google Chrome and all seems fine for me. I assume you've tried uninstalling and re-installing the extensions? I'm not seeing any issues raised on the React Dev Tools repo either.

**Comment by nicewaytodoit** [comment]
Auto-magically start working again, I do not know what happen but I am puzzled.
