### ISSUE TITLE
Bug: h key not working in dispatcher text box.

### ISSUE THREAD

**Issue by LeeWannacott** [reduxjs/redux-devtools#841]
My `h` key on my keyboard isn't working in the dispatcher text box. My `h` key is clearly working elsewhere and other keys are working in the dispatcher text box?
![hkey2](https://user-images.githubusercontent.com/49783296/132144745-d8f808ae-f27a-4f4e-89a1-de7de18df4ac.png)

Using Chrome Version 92.0.4515.131 (Official Build) (64-bit) and v2.17.2 of Redux DevTools

**Comment by LeeWannacott** [comment]
I opened in a new window and it seemed to fix it. Weird. ¯\_(ツ)_/¯

**Comment by AlanCarlyle** [comment]
Just had the same issue and it seems to be specific to when Redux DevTools is embedded in Chrome Developer Tools.
I disabled all extension and restarted and it was still happening.

**Comment by LeeWannacott** [comment]
@AlanCarlyle Well good to know it wasn't just me. I thought it was such an esoteric issue that it must of been specific to me; so I closed the issue.
