### ISSUE TITLE
Last Update to tool on Firefox was in 2019

### ISSUE THREAD

**Issue by pszponder** [reduxjs/redux-devtools#933]
Are these devtools still being supported for firefox? On the firefox addons page, the last update was in Jan 2019 but the chrome version was updated just a few months ago. I'm just trying to figure out if I need to switch to chrome, thanks!

**Comment by Methuselah96** [comment]
The Firefox extension is still supported. The reason for the Chrome extension release was [updating the permissions ](https://github.com/reduxjs/redux-devtools/issues/713) because it got taken down.
