### ISSUE TITLE
Use of 'process' in redux-devtools-inspector-monitor

### ISSUE THREAD

**Issue by michaeljohansen** [reduxjs/redux-devtools#937]
The `@redux-devtools/inspector-monitor` depends on `chalk` which is intended for Node usage and expects both the `global` object and a `process` object. I can hotfix this problem in a newer browser by doing:

```
const global = globalThis;
const process = globalThis;
```

However, this creates problems elsewhere when other libraries expect e.g. `process` to be undefined to determine whether the library is running in a browser or in Node. Since this is a frontend library I suggest attempting to replace Chalk.

```
index.js:8 Uncaught ReferenceError: process is not defined
    at node_modules/jsondiffpatch/node_modules/chalk/index.js (index.js:8)
    at node_modules/jsondiffpatch/dist/jsondiffpatch.esm.js (main.js:14)
    at node_modules/@redux-devtools/inspector-monitor/lib/createDiffPatcher.js (createDiffPatcher.ts:1)
    at node_modules/@redux-devtools/inspector-monitor/lib/DevtoolsInspector.js (DevtoolsInspector.tsx:23)
    at node_modules/@redux-devtools/inspector-monitor/lib/index.js (index.ts:1)
```

**Comment by Methuselah96** [comment]
Interesting. In my setup it uses the UMD version of `jsondiffpatch` defined by the [`"browser"` entry](https://github.com/benjamine/jsondiffpatch/blob/master/package.json) which excludes `chalk` for this reason. What does your setup look like?

**Comment by michaeljohansen** [comment]
Mine seems to be using the [ESM version](https://github.com/benjamine/jsondiffpatch/blob/master/package.json#L11). The relevant project is a React + Node app. I've recently rewritten the project to use ESM throughout. I use [Vite](https://vitejs.dev/) for building the React part. My `package.json` has `type: module`.

**Comment by Methuselah96** [comment]
Got it, looks like you're running into the behavior described in https://github.com/vitejs/vite/issues/2329. Sounds like the best solution is for `jsondiffpatch` to add conditional `exports` fields. Feel free to open an issue with `jsondiffpatch` or I can do so when I find the time.
