### ISSUE TITLE
How to setup local development to watch changes in dependency packages ?

### ISSUE THREAD

**Issue by 80avin** [reduxjs/redux-devtools#966]
Could you please provide setup instructions for this monorepo ?

While I can test by building the packages, I cannot do live development properly as it doesn't watch the dependent packages.

Ex. I'm running `start` in `packages/redux-devtools-app` which depends on `@redux-devtools/ui`. But when I make changes in `packages\redux-devtools-ui\src\Tabs\TabsHeader.tsx`, the changes aren't reflected in the running app.

Added following to `packages\redux-devtools-app\webpack.config.ts`
```js
watch: true,
devServer: {
  hot: true,
  port: 3000,
  open: true,
}
```
and ran `start` script doesn't do the job.

My familiarity with monorepos is very less, and hence after several days of struggle, couldn't find a solution.
It would be nice if you help me out.

**Comment by 80avin** [comment]
Found a workaround with `nodemon`

**Comment by bk973** [comment]
Close this issue
