### ISSUE TITLE
Feedback on new v3.0 UI

### ISSUE THREAD

**Issue by markerikson** [reduxjs/redux-devtools#995]
Per discussion in Reactiflux, congrats on getting this out the door!

My main nitpick, as I noted earlier, is that all of the "data" areas of the UI (actions list, action/state tab contents, RTKQ tab) are using a variable-width font, regardless of whether the main theme setting is "Default" or "Material".  In this case it looks like the font is `Source Sans Pro`:

![image](https://user-images.githubusercontent.com/1128784/148651369-fa2ee09c-ae58-4392-b931-b1602a7e1d39.png)

I _personally_ would really prefer to still have all the actual data in a fixed-width / monospace font.

It would also be helpful to have a font size setting for the content areas, and _maybe_ bump up the default font size for the content just a bit.

Interestingly, it looks like the "Log Monitor" _is_ using a monospace font, "Source Code Pro":

![image](https://user-images.githubusercontent.com/1128784/148651385-24c20c74-02dc-4c31-9797-12b10bd74db8.png)

Also: the "tabs"-ish buttons on the main panel are capitalized ("Actions", "State"), but the buttons on the RTKQ panel are all lower-case ("query", "api").

**Comment by FaberVitale** [comment]
> Also: the "tabs"-ish buttons on the main panel are capitalized ("Actions", "State"), but the buttons on the RTKQ panel are all lower-case ("query", "api").

My bad :)

I'll make a PR.

**Comment by jjspace** [comment]
> My main nitpick, as I noted earlier, is that all of the "data" areas of the UI (actions list, action/state tab contents, RTKQ tab) are using a variable-width font

> It would also be helpful to have a font size setting for the content areas, and maybe bump up the default font size for the content just a bit.

I came looking to open an issue on exactly these items. It's much harder to read after the update for me and I'd love more control over the font used. At the very least a "small, medium, large" setting for size but a monospace font is also greatly desired.

**Comment by markerikson** [comment]
Related: the "Stack Trace" pane seems to have lost any formatting as well:

![image](https://user-images.githubusercontent.com/1128784/149675465-96d5d3f0-f8d6-4d4d-b818-118b9c88f4b8.png)

**Comment by Methuselah96** [comment]
That looks the same (except for the font which I expect to fix soon) as 2.17:
![image](https://user-images.githubusercontent.com/693755/149680810-8753e244-8150-4c9f-8555-964d3c148c4e.png)

**Comment by Methuselah96** [comment]
I think it's missing the actual code in the stack frames which is why it looks to be missing formatting. I think if it showed the actual code it would look more normal, but I'll have to double-check that later.

**Comment by markerikson** [comment]
Oh yeah, _that's_ why it looks weird :)

I know that Mihail completely restyled things after I initially ported the CRA dev overlay over into this codebase (dark theme, etc).  Code snippets are kinda important though :)

**Comment by Methuselah96** [comment]
Yeah, I think it works or doesn't work depending which kind of sourcemap you use. I've been meaning to look into it, but figured since it was already broken in 2.17 I'd wait until releasing 3.0 to look into why it was broken.

**Comment by Methuselah96** [comment]
Looks like it's working for `devtool: 'source-map'`, but not `devtool: 'eval-source-map'`.

**Comment by jtiscione** [comment]
Does anyone know how to make the font larger? Or the latest version that had legible fonts?
![Screen Shot 2022-01-18 at 10 48 14 AM](https://user-images.githubusercontent.com/5413726/149991327-9846fea0-8b8c-4cbf-affe-9aad9a53b97c.png)
I can't read this at all.
